### ISSUE TITLE
Gracefully Crash on missing dependencies

### ISSUE THREAD

**Issue by BlackstoneEngineering** [ARMmbed/mbed-cli#134]
Because mbed-cli will wrap so many other tools there should be a system in place so when a user invokes a command and the pre-requisites are missing the tool can gracefully exit and give the user a message with suggested fixes.

## Example: git not installed
In this example git cannot be found in the users path. The tool prompts the user to install it as it is outside the scope of our duty to install this for the user. Alternatively we could provide a mbed-cli.exe pckage like previously that wraps all these tools together. 
```shell
$ mbed clone myawesomeproject
. . . . 
[Error : `git` not found] 
Suggested fix: If git is installed on your system make sure it is linked in the global PATH. If git is not installed try installing it using one of the methods below. Or checkout this youtube video on the error (Link to video)
Windows - install the git toolbelt (Link goes here), make sure to select a global install / modify env path
Mac - install git toolbel (link goes here)
Linux (Ubuntu) - run `sudo apt-get install git`
Linux (Arch) - run `sudo pacman -Ss git`
```

## Example : greentea not installed
In this example greentea is not installed on the system, thus preventing tests from being run, the tool tells the user it cannot find greentea and asks if the CLI should install it. If the user says yes then mbed-cli will run `pip install -U greentea` in the background.
```shell
$ mbed test
. . . . . 
[Error : greentea not found]
Would you like to install greentea now? (Y/N) $ |
```

**Comment by screamerbg** [comment]
Is already implemented as mbed-os tools auto-installation of dependencies @theotherjimmy
