### ISSUE TITLE
Export test request

### ISSUE THREAD

**Issue by 0xc0170** [ARMmbed/mbed-cli#199]
we provide arguments to compile tests ``mbed compile --tests -n name``. This should be expanded to exporters, as people would like to debug their tests.

A proposal:
``mbed export --test -n name`` this would gets expanded to ``--source=test/path`` (=this is current workaround that has a bug though but easy to fix in the project file to edit test file path).

cc @adbridge @bridadan

**Comment by screamerbg** [comment]
Already being tracked in this PR https://github.com/ARMmbed/mbed-os/pull/2208
