### ISSUE TITLE
There is no command line option validation

### ISSUE THREAD

**Issue by LiyouZhou** [ARMmbed/mbed-cli#201]
`mbed deploy --protocol sssh`, `mbed deploy -protocol sssh` both proceeded without problem ignoring the wrong options.

**Comment by theotherjimmy** [comment]
@LiyouZhou There's definitely command line validation, just not for the `--protocol` switch. Try compiling for a `K649` or something, and you'll see it.

**Comment by LiyouZhou** [comment]
@theotherjimmy, yes I understand there is some command line validation. I think the original issue was regarding the --protocol command. Also this issue was raised 2 years ago, hence thing might have changed a lot.  If you think this ticket no longer applies, feel free to close.

**Comment by adbridge** [comment]
*Issue header has missing or incorrectly filled in fields! Please fix.*

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
