### ISSUE TITLE
Loop through all "submodules"

### ISSUE THREAD

**Issue by korjaa** [ARMmbed/mbed-cli#202]
Could we have a possibility to run a command in all repositories in the project like **git submodule foreach** does? Maybe **mbed foreach**.

This question was raised by an Windows user in the SiP workshop because as I understood there is an issue with Windows git that it sets core.filemode as true when cloning repository and that makes git track file mode changes (all files are displayed as modified by git). Because this option is set per repository while cloning, it overrides the global core.filemode configuration. This means that you have to go through all the git repositories by hand and set core.filemode to false.

UPDATE:
Windows git does follow global core.filemode configuration BUT if you clone your repository before setting it, it does not apply. And as default it is set to true.

Maybe something like this?

```
#!/bin/bash
# mbed_foreach.sh "<command>"
find -type f -name "*.lib" -print0 | sed -z 's/\.lib$//' | xargs -0 -L1 -I{} bash -c "cd \$1; $@" -- {}
```

Of course there is the issue that not all repositories are git, so you need to keep that in mind. Maybe provide a flag "mbed foreach -g" for git repositories.

@screamerbg

**Comment by adbridge** [comment]
*Issue header has missing or incorrectly filled in fields! Please fix.*

**Comment by mark-edgeworth** [comment]
This is not something that we'd consider adding as it would make the mbed CLI far more complex for little gain. As you have kindly published a way of doing this using the Windows command line I'd move to close this issue if we can please.
