### ISSUE TITLE
Build directory should not be hidden

### ISSUE THREAD

**Issue by jaustin** [ARMmbed/mbed-cli#206]
At the moment after completing a build, the binary created lives in the hidden .build directory

This makes it hard for the user to find.

**Comment by andcor02** [comment]
Any update on this?

While its clear we can choose another build directory using --build, if we look at the handbook for blinky example there isn't any mention of this. Had people commenting on windows without hidden folders viewed having no clue where their build files are. Viewing hidden folders on mac is even more cumbersome and reports of people thinking CLI is broken.

**Comment by sg-** [comment]
@theotherjimmy @sarahmarshy Can you update this for exporters and build tools?

**Comment by MarceloSalazar** [comment]
I have now hit this....
@theotherjimmy @sarahmarshy could you please update the tools and make the build directory visible?

**Comment by screamerbg** [comment]
It's a bit more complicated than just updating the tools. Will have this scheduled for the next round of changes (~2w)

**Comment by sarahmarshy** [comment]
Looks like this is the line in question: https://github.com/ARMmbed/mbed-os/blob/master/tools/toolchains/__init__.py#L543

(In addition to the steps that actually put files there).

We should decide on a name to be added to the ignore ('mbed_build'?)

**Comment by screamerbg** [comment]
Now merged and part of the mbed CLI 0.9.10 release. Please reopen if the issue persists.
