### ISSUE TITLE
Improve user experience at installing mbed tools

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/mbed-cli#218]
Currently, we need to install Python, pip, git, mercurial, mbed-cli.

maybe @screamerbg and @BlackstoneEngineering can help?

**Comment by screamerbg** [comment]
There is already Windows installer. and @BlackstoneEngineering is working on Mac installer. @MarceloSalazar are you happy to write a new feature requirement for installers that bundle up Mbed CLI, python modules, git, hg, and latest Mbed OS for pre-cached operation. cc @arekzaluski about having Mbed OS git index as part of the installer which can be used as pre-populated cache.
