### ISSUE TITLE
mbed-cli does not find ARM compiler in linux (with ARM_PATH defined)

### ISSUE THREAD

**Issue by teetak01** [ARMmbed/mbed-cli#219]
Trying to compile with ARM compiler -- Getting this kind of failure:
```
Building project mbed-client-testapp (K64F, ARM)
ERROR: run_cmd: Command 'C:/Program Files/ARM/bin/armcc' can't be found
ERROR: run_cmd: Command 'C:/Program Files/ARM/bin/armcc' can't be found
```
I have specified as per README:
```
Product: ARM Compiler 5.06
Component: ARM Compiler 5.06 update 1 (build 61)
Tool: armcc [4d35ad]
```
```
teetak01@machine:~/dev/mbed-client-testapp (bootstrap)$ which armcc
/home/teetak01/ARM_Compiler_5.06u1/bin/armcc
```
```
teetak01@machine:~/dev/mbed-client-testapp (bootstrap)$ env | grep ARM_PATH
GCC_ARM_PATH=/usr/bin/arm-none-eabi-gcc
ARM_PATH=/home/teetak01/ARM_Compiler_5.06u1
```
```
Command-line code management tool for ARM mbed OS - http://www.mbed.com
version 0.7.3
```

**Comment by teetak01** [comment]
Any progress on this? I now installed a new environment and armcc there. mbed-cli does not respect the environmental variables:
`export ARM_PATH="/home/teetak01/ARM_Compiler_5.06u3/"`

It also does not follow the mbed_settings.py file in my root-folder for the project. Instead it is reading the ARMCC path from mbed-os/tools/settings.py, which by default is pointing to some windows-folder ARM_PATH = "C:/Keil_v5/ARM/ARMCC".

I had to manually change the path here to my installed path and of course changing it there will destroy it when ever mbed-os folder is updated.

**Comment by jupe** [comment]
this should be very easy to fix so when we get it?

**Comment by screamerbg** [comment]
This is covered in the toolchain selection in the mbed CLI manual https://github.com/ARMmbed/mbed-cli/blob/master/README.md#toolchain-selection

**Comment by teetak01** [comment]
Thanks, missed those updates.

**Comment by jupe** [comment]
I'm not very satisfied with this solution -> not very good user experience if every user have to run some mbed-cli commands before using compiler. Why mbed-cli couldn't detect those environment variables instead?

**Comment by bridadan** [comment]
@jupe There is a PR up now that adds this capability I believe, as well as improved errors when your toolchain is not found: https://github.com/ARMmbed/mbed-os/pull/2418

**Comment by matthieu-labas** [comment]
Sorry to bring this old thread back up but I'm having the same problem with an mbed-cli installed last week:

```
make.py: error: Could not find executable for ARM.
Currently set search path: /home/matthieu/ARM_Compiler_5.06u6/bin
```

`armcc` is there, and seems functional. I have also edited the `mbed_settings.py` with `ARM_PATH = /home/matthieu/ARM_Compiler_5.06u6/bin` but the message still shows up...

**Comment by bridadan** [comment]
@matthieu-labas which version of Mbed OS are you using?

**Comment by theotherjimmy** [comment]
@matthieu-labas Set your `ARM_PATH` to `/home/matthieu/ARM_Compiler_5.06u6`.

**Comment by theotherjimmy** [comment]
See https://os.mbed.com/docs/mbed-os/v5.11/tools/after-installation-configuring-mbed-cli.html for more info.

**Comment by matthieu-labas** [comment]
@theotherjimmy you're right, the `bin` was wrong. I don't remember where I read we had to add it...
@bridadan MbedOS 5.11.4 with mbed CLI 1.9.0 (in case it makes a difference).

Sorry for bothering on such an rtfm question!
