### ISSUE TITLE
Need a command to update dependency versions

### ISSUE THREAD

**Issue by LiyouZhou** [ARMmbed/mbed-cli#223]
### Description
- Type: Enhancement
- Priority: Minor

---
## Enhancement

**Reason to enhance/problem with existing solution**
A module's dependencies can get out of date. Once in a while I want to update all dependencies to its latest commit. Currently only thing I can do is go into the dependency folder and call mbed update. When you have many dependencies, this is costing me a lot of time.
**Suggested enhancement**
An command such as `mbed update dependencies` that can go into the dependency folders for me and update them as well as my .lib file references.

**Comment by adbridge** [comment]
*Issue header has missing or incorrectly filled in fields! Please fix.*

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
