### ISSUE TITLE
Support mirror of mbed os

### ISSUE THREAD

**Issue by jenia81** [ARMmbed/mbed-cli#227]
Currently, "mbed import" takes a **very** long time.
Possible solution is that "mbed import" will support importing of a mirrored tree/s.
Meaning, user will mirror clone mbed-os repository (and possibly all its' dependencies) and mbed import will import those trees from the mirror location.

**Comment by screamerbg** [comment]
Mbed CLI 1.5 and onwards (1.7.1 is the latest as I'm writing this) has a default caching feature. Hopefully this address the long import times concerns. Closing this issue as it's very old but feel free to reopen if you feel that the caching feature doesn't solve your issue.
