### ISSUE TITLE
SSH support

### ISSUE THREAD

**Issue by BlackstoneEngineering** [ARMmbed/mbed-cli#232]
## Problem

I have configured Git to use ssh keys on my machine but the tool does not pick this up automatically. I can force it to use ssh every time by using the `--protocol ssh` flag, but since I have already made SSH the default way I use git I want this to just work, no fuss.
## Solution

Check if user has configured SSH keys for git, if so use them. 
#### Options
- Can check if `~/.ssh/id_rsa` exists
- Check if github.com is in `~/.ssh/known-hosts`

**Comment by theotherjimmy** [comment]
So we're done here.
