### ISSUE TITLE
Compile/run for multiple toolchains and multiple targets

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/mbed-cli#236]
This is a feature request.

I want to compile my program and run tests for multiple toolchains (ARM, GCC_ARM, IAR) and targets (K64F, LPC1768, RZ_A1H, etc) with 1 command.
Something like this would really help:

```
mbed compile -t ARM,GCC_ARM,IAR -m K64F,LPC1768,RZ_A1H
```

and compile & run tests:

```
mbed test -t ARM,GCC_ARM,IAR -m K64F,LPC1768,RZ_A1H
```

**Comment by adbridge** [comment]
*Issue header has missing or incorrectly filled in fields! Please fix.*

**Comment by mark-edgeworth** [comment]
You can already do this by scripting the mbed CLI externally. Alternatively there appear to be various other scripts lurking around that do something similar. I'm closing this one as we're unlikely to implement it.
