### ISSUE TITLE
SSH behaviour undesirable on libraries

### ISSUE THREAD

**Issue by bremoran** [ARMmbed/mbed-cli#249]
When a module includes a library specified with https, adding the module with a SSH URL results in undesirable behaviour:

```
annirak:~/workspace/mbed-os-ucmm (master) $ mbed add git@github.com:ARMmbed/update-client-common.git
[mbed] Adding library "update-client-common" from "git@github.com:ARMmbed/update-client-common.git/" at latest revision in the current branch
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
[mbed] Adding library "update-client-common/atomic-queue" from "https://github.com/ARMmbed/atomic-queue/" at rev #64c817760497
Username for 'https://github.com':
```

If a user has authenticated with ssh for a top-level module, ssh should be assumed for each submodule, unless ssh fails, then https should be used as a fallback.

This might be easier if it were possible to specify a git repo with no protocol. e.g. `github.com:ARMmbed/update-client-common.git` can easily be used as either a ssh or https repo specifier.

**Comment by theotherjimmy** [comment]
As mentioned above, `--protocol ssh` applies to all git interaction in a session.
