### ISSUE TITLE
mbed CLI should show warning on duplicate dependencies

### ISSUE THREAD

**Issue by bremoran** [ARMmbed/mbed-cli#250]
If module A depends on module B and module C depends on module B, then doing the following will result in two instances of module B being compiled, which will result in linker clashes.

```
mbed new test
cd test
mbed add modulea
mbed add modulec
```

**Comment by adbridge** [comment]
*Issue header has missing or incorrectly filled in fields! Please fix.*

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
