### ISSUE TITLE
mbed-cli should report the active tool for all output

### ISSUE THREAD

**Issue by bremoran** [ARMmbed/mbed-cli#251]
When a message is printed by mbed-cli, it's not clear where it is coming from. This leads to some situations where it appears that mbed-cli is asking for account credentials. This could be improved by prefixing each line of text with the name of the tool that generated it, which would make it clear where output is coming from and which tool is receiving input.

**Comment by adbridge** [comment]
*Issue header has missing or incorrectly filled in fields! Please fix.*

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
