### ISSUE TITLE
No way to build tests with debug symbols

### ISSUE THREAD

**Issue by bremoran** [ARMmbed/mbed-cli#272]
There is no way to pass any flags to `mbed test` in order to enable building of debug symbols

**Comment by screamerbg** [comment]
@bridadan Are you happy to update the docs regarding debug symbols?

**Comment by bridadan** [comment]
@screamerbg It's a little more complicated than updating the docs, since the `-o` option needs to be added to mbed-cli itself. I can look into this though.

**Comment by screamerbg** [comment]
@bridadan I'll add this to `mbed compile`. Happy to add it to `mbed test`?

**Comment by bridadan** [comment]
Got a PR up :) https://github.com/ARMmbed/mbed-cli/pull/311

**Comment by screamerbg** [comment]
Now merged with master. Will be introduce with the next mbed CLI release.
