### ISSUE TITLE
Running the mbed command always results in 'failed to create process'

### ISSUE THREAD

**Issue by emidttun** [ARMmbed/mbed-cli#273]
The main problem as I see it is the lack of feedback to resolve the issue. But it could be a Python issues.

Main suspect is that Python is installed in "Program Files\", as is default for Python 3.5, and there is an issue with spaces in the path.

Environment info:
- Windows 7
- Python 3.5.1
- pip 8.1.2

**Comment by screamerbg** [comment]
The documentation now states that Python 2.7 is required
