### ISSUE TITLE
wildcards in test -n doesnt work with ZSH

### ISSUE THREAD

**Issue by BlackstoneEngineering** [ARMmbed/mbed-cli#276]
## Problem
Running a command like this `mbed test -n tests-api-*` should run all tests in the TESTS/API/* folder, but under ZSH this doesnt work. Instead ZSH barfs like this `zsh: no matches found: tests-api-*`.

## Solution
unknown, look into using wild cards in zsh

### importance
low, just logging bug for future reference

**Comment by screamerbg** [comment]
@BlackstoneEngineering how would you like to proceed then?

**Comment by screamerbg** [comment]
The documentation now contains information about shells that are exploding * into file names. https://github.com/ARMmbed/mbed-cli#limiting-the-test-scope
