### ISSUE TITLE
Inconsistent behavior when compiling application and static library

### ISSUE THREAD

**Issue by mottigondabi** [ARMmbed/mbed-cli#288]
Given the following work-space:

|-- TESTS
|-- **atmel-rf-driver**
|-- **mbed-os**
|-- oma_client.cpp
|-- oma_client.h
|-- mbed_client_config.h
|-- mbed_settings.py
|-- mbed_settings.pyc

**Compiling application** e.g.: `mbed compile -m K64F -t GCC_ARM` does not require using a specific include paths definitions for mbed-os when compiling from tree top level (assuming oma-client.cpp has main() function)

**Compiling static library** e.g.: `mbed compile --library artifact-name my_oma_lib -m K64F -t GCC_ARM` requires specifying the actual include paths needed when compiling from tree top level (using `--source=<path-to-dir>`). oma-client.cpp doesn't have main() function.

**Expected behavior:**
compiling for either application, test or static-library should act the same manner.

@jenia81 
@screamerbg 
@trianglee

**Comment by screamerbg** [comment]
@mottigondabi any news on this?

**Comment by mottigondabi** [comment]
redundant. closing this issue.
