### ISSUE TITLE
Hardcoded `mbed-os` directory needs to be documented.

### ISSUE THREAD

**Issue by SeppoTakalo** [ARMmbed/mbed-cli#296]
The `mbed` command assumes to find mbed OS tools from directory `mbed-os/tools`

This may cause problems if mbed OS is cloned under different name, for example `mbed`

```
$ mbed deploy
[mbed] Updating library "atmel-rf-driver" to rev #a16a4ed6f6e8
[mbed] Updating library "mbed" to rev #b171a9c4b853
[mbed] Couldn't find build tools in your program. Downloading the mbed 2.0 SDK tools...
```

I did not see that documentation clearly states that mbed OS should be cloned under name `mbed-os`
I would recommend adding that clause somewhere so others won't make the same mistake.

**Comment by screamerbg** [comment]
It's now documented. Further more, it is possible to configure the path to mbed-os via Mbed CLI config variable #626
