### ISSUE TITLE
`mbed update` should tell about leftover modules (assuming that `--clean` is not used)

### ISSUE THREAD

**Issue by janjongboom** [ARMmbed/mbed-cli#298]
1. Got a project, that in upstream has removed a module
2. `git pull && mbed update`
3. Build
4. Weird errors

This is because the .lib file is gone, but the actual module code is still in the tree. We should ask the user to remove untracked modules (or check if the directory is dirty, and if not, remove it).

**Comment by screamerbg** [comment]
I believe this is resolved. Please reopen if needed.
