### ISSUE TITLE
config - need way to list config

### ISSUE THREAD

**Issue by BlackstoneEngineering** [ARMmbed/mbed-cli#302]
## Problem
There is no way to know the current config for a repo, you must know what keys to type in to get their values. There needs to be a command to let you see all config for a repo at a glance.

## Solution
Add a `-l` or '-ls` option to `config` so you can do something like this

```
$mbed config toolchain tool
$mbed config target targ
$mbed config -G protocol ssh
.....

$mbed config -ls
[mbed] Configuration is:
  Local
    toolchain : tool
    target : targ
  Global
    protocol : ssh
```

This would implicitly only show globals if they are not explicitly overridden in the local context.

**Comment by bogdanm** [comment]
You can do `mbed compile --config`. A `mbed config` command used to exist, but was removed for reasons that I personally never understood.

**Comment by BlackstoneEngineering** [comment]
right, i'm asking, as US lead for Developer enablement, to put it back. Less as a engineering thing and more as a story thing. if we can set it we need to be able to validate that we set it correctly. This will prevent endless headaches in workshops and trainings.

**Comment by screamerbg** [comment]
Example:

```
[mbed] Global config:
ARM_PATH=C:\Program Files\ARM
CACHE=D:\Temp\repo-cache
TOOLCHAIN=ARM
TARGET=K64F

[mbed] Local config (D:\Work\examples\mbed-os-example-ble-BatteryLevel):
PROTOCOL=ssh
```

**Comment by bridadan** [comment]
@bogdanm Pretty sure @BlackstoneEngineering is talking about mbed CLI config, not the mbed OS config system values.

**Comment by bogdanm** [comment]
I believe you are completely right :grin:

**Comment by screamerbg** [comment]
Now part of mbed CLI 0.9.1 release
