### ISSUE TITLE
publish - hg should use `-m` by default

### ISSUE THREAD

**Issue by BlackstoneEngineering** [ARMmbed/mbed-cli#304]
## Problem
When committing a mercurial (hg) repository mbed-cli opens an editor to make the commit. This is somewhat confusing to users as you will have to type in the information for the commit, then save, then close the editor for mbed-cli to continue. It is entirely possibl for users to leave the window open and get frustrated with mbed-cli for not progressing. 

## Solution
detect if the user types something before pressing enter. If something is input then use that as the commit message, otherwise continue to open the editor. (or even better yet if nothing is specified then submit an empty commit message of `""`)

**Comment by screamerbg** [comment]
`mbed publish` already supports `-m` switch which is passed to both `git` and `hg`. Regarding opening editor etc, both Git and Hg would open an editor when `-m` is not specified.
