### ISSUE TITLE
publish - no changes needs error message

### ISSUE THREAD

**Issue by BlackstoneEngineering** [ARMmbed/mbed-cli#305]
## Problem
Currently, if a user does `mbed publish` but no changes have been made to commit and push then the message looks like this 
```
> mbed publish
[mbed] Checking for local modifications...
/
>
```

The problem is that this is very confusing, the user will say "I tried to publish, what the hell?" they will then run the command multiple times and get annoyed, not realizing that there are no changes to be published.

## Solution
Add message similar to what git has, `No new changes made to publish. Please make a change and then try to publish.`

**Comment by screamerbg** [comment]
Now part of mbed CLI 0.9.1 release
