### ISSUE TITLE
How to ignore a folder

### ISSUE THREAD

**Issue by janjongboom** [ARMmbed/mbed-cli#324]
I have a project which also contains a web app. Now when I build the project it wants to build all the native extensions for that web app too. How can I pass in an option to the mighty compiler to tell it to ignore that folder (should work in both ARMCC and GCC).

**Comment by bridadan** [comment]
You should be able to use `.mbedignore` files: https://github.com/ARMmbed/mbed-os/blob/master/docs/ignoring_files_from_build.md

**Comment by janjongboom** [comment]
Yep, great. Thanks @bridadan .
