### ISSUE TITLE
[mbed] ERROR: Unknown Error: nothing to repeat

### ISSUE THREAD

**Issue by jsplyy** [ARMmbed/mbed-cli#328]
![capture](https://cloud.githubusercontent.com/assets/3600912/17919967/f80ca41a-6a03-11e6-9328-692658db23a6.PNG)

hi:
Creating a new program for mbed OS 5 fail. how to deal with it?

**Comment by screamerbg** [comment]
Thanks for reporting this. Do you think you could execute the same command with '-vv' and paste the output here? Thanks in advance.

**Comment by smam-emb** [comment]
You need to use Python version >= 2.7.9. See the following link 
https://github.com/ARMmbed/mbed-cli/issues/325

**Comment by screamerbg** [comment]
@jsplyy @smam-emb Is this still an issue with the latest mbed CLI (0.9.5)?

**Comment by smam-emb** [comment]
For me this was resolved after downloading the corrrect Python version (including the minor version). Initially I had installed Python 2.7.

**Comment by jsplyy** [comment]
Yes, when I update the python from 2.7.3 to python 2.7.12,it was resolved.

**Comment by bridadan** [comment]
@jsplyy Glad you were able to find a solution! Closing.
