### ISSUE TITLE
Equivalent of yotta --config with mbed-cli

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [ARMmbed/mbed-cli#329]
With yotta there was a possibility to select which config.json was used for the build (`yotta --config my-config.json`.

Is there a similar possibility with mbed-cli to choose a different file than mbed_app.json?

@MarceloSalazar @daniel-cesarini-tridonic-com

**Comment by screamerbg** [comment]
CC @bogdanm

**Comment by theotherjimmy** [comment]
We could support a similar option in the mbed-os tools, and propagate that option up to mbed-cli. It would be all on the config system though.

**Comment by screamerbg** [comment]
@theotherjimmy do you think you could look at introducing the option in the mbed-os tools? Adding the help to mbed CLI is trivial really. Also, could you please create issue under https://github.com/ARMmbed/mbed-os?

**Comment by screamerbg** [comment]
Implemented with https://github.com/ARMmbed/mbed-cli/pull/337. This would be introduced with the next mbed CLI release.

**Comment by daniel-cesarini-tridonic-com** [comment]
@screamerbg @theotherjimmy Thank you. 

We will try this out as soon as it is ready and provide feedback on whether it solves our issue.

**Comment by screamerbg** [comment]
I believe this is implemented and now live. Please reopen if that's not the case

**Comment by markus-becker-tridonic-com** [comment]
@screamerbg --app-config only works with an updated mbed-os, or?

**Comment by bridadan** [comment]
@markus-becker-tridonic-com I believe this was added in version 5.1.4 of mbed OS. This was the PR that added this functionality: https://github.com/ARMmbed/mbed-os/pull/2593
