### ISSUE TITLE
mbed new should fetch the latest stable release, by default

### ISSUE THREAD

**Issue by AlessandroA** [ARMmbed/mbed-cli#330]
At the moment if I run

```bash
$ mbed new myapp
```

the tool fetches the HEAD of ARMmbed/mbed-os master, which is prone to bugs and instabilities.

A sensible default would be to fetch the latest stable release/tag.

See for example: https://github.com/ARMmbed/uvisor/issues/312.

@screamerbg @geky @sg-

**Comment by sg-** [comment]
tag "latest" created. mbed CLI can now pull against this.

**Comment by screamerbg** [comment]
Thanks. Will be introduced in the next mbed CLI release

**Comment by screamerbg** [comment]
This is now supported in the latest version of mbed CLI (0.9.5)
