### ISSUE TITLE
Compile for debugging requires clean flag 

### ISSUE THREAD

**Issue by arekzaluski** [ARMmbed/mbed-cli#338]
Compile with debugging symbols requires -c (clean) flag to work while switching from standard build. mbed-cli should allow to build with debugging symbols without specifying additional clean flag. Currently it it is difficult to use it in IDE because it requires clean flag every time when it is being built for debugging.

**Comment by bridadan** [comment]
This is similar to the issue raised here: https://github.com/ARMmbed/mbed-os/issues/2412

We'd basically need to store what compile options are used for each build and put it in the build directory, compare it with what the current build options are, and trigger a clean build if something changed.

**Comment by screamerbg** [comment]
cc @theotherjimmy

**Comment by screamerbg** [comment]
@arekzaluski This is now supported through the --profile option. Please reopen if this doesn't resolve your request.
