### ISSUE TITLE
Method to instruct mbed-cli to ignore certain source files

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [ARMmbed/mbed-cli#354]
What is the recommended method of telling mbed-cli to not compile certain source files?

Previously with mbed3/yotta one could exclude files from compilation with CMakeLists.txt. I was unable to find information about this on https://docs.mbed.com/docs/mbed-os-handbook/en/5.1/dev_tools/cli/.

**Comment by markus-becker-tridonic-com** [comment]
@MarceloSalazar

**Comment by MarceloSalazar** [comment]
This is possible by using the '.mbedignore' files.
https://github.com/ARMmbed/mbed-os/blob/master/docs/ignoring_files_from_build.md

**Comment by markus-becker-tridonic-com** [comment]
Thanks.
