### ISSUE TITLE
user.name config option doesn't save

### ISSUE THREAD

**Issue by cwq9999** [ARMmbed/mbed-cli#357]
I recently tried out the mbed-cli and like the features, however had to enter in my user name numerous times. I found that there is both:

mbed config --global user.name 
and
mbed config user.name

If I use either and place my user name at the end the cmd line tells me that the default user.name has been set; however, when I then type in:
mbed config --global user.name 
and
mbed config user.name

I get the message saying no user.name has been set. I just upgraded the mbed-cli thinking maybe was due to an old version but same issue persists. I'm using a PC and doing all this via cmd prompt.

**Comment by screamerbg** [comment]
Fixed in latest mbed CLI (v1.0.0
