### ISSUE TITLE
Python isn't robust

### ISSUE THREAD

**Issue by Timmmm** [ARMmbed/mbed-cli#359]
Python is fun and all, but it saddens me a bit to see that a tool like this which should be easy to install and reliable is written in Python. It leads to nonsense like:
1. I run `c:\Python27\scripts\pip install mbed-cli`. It somehow finds one of my other Python installation at `c:\yotta\python\lib\site-packages` and installs mbed-cli there. Wtf?
2. I run `c:\yotta\python\scripts\mbed new mything`. It downloads some stuff and then complains that `pip` is not in the path. Again, wtf? Why does it even need to use pip?

Honestly Python is a nice language but as a program it has never given me anything but problems. mBed is never going to displace Arduino as long as you have to put up with stuff like this.

I would suggest rewriting in Go, which is the approach taken by Mynewt.

/rant

**Comment by theotherjimmy** [comment]
Sorry, rant's are not issues. We are not planning on moving away from python for the time being.
