### ISSUE TITLE
mbed-cli provides out of date command parameters and help

### ISSUE THREAD

**Issue by bulislaw** [ARMmbed/mbed-cli#370]
Each mbed-cli defines available commands together with parameters and help. That's inherently broken as in case it's changed in mbed-os (where the commands are defined) requires corresponding change to mbed-cli. Which makes it hard to maintain and is error prone.

The parameter/help definition should be removed from mbed-cli, mbed-os tools do the parameter validation and help on their own anyway.

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-469

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
