### ISSUE TITLE
github/pypi version mismatch

### ISSUE THREAD

**Issue by bogdanm** [ARMmbed/mbed-cli#372]
According to https://github.com/ARMmbed/mbed-cli/blob/master/setup.py#L21, the latest version of this package is 0.9.7. However, its version on PyPI is 0.9.9 (https://pypi.python.org/pypi/mbed-cli/0.9.9)

**Comment by screamerbg** [comment]
@bogdanm Looks like a commit didn't reach Github in previous PR hence I sent a separate PR. This is now corrected. Thanks for reporting this!
