### ISSUE TITLE
mbed-cli does not support Python3

### ISSUE THREAD

**Issue by JanneKiiskila** [ARMmbed/mbed-cli#376]
Documentation (README.md) refers to mbed-cli being a Python script and it's tested on Python 2.7.

https://github.com/ARMmbed/mbed-cli/blob/master/README.md#installation

However, reality is that it does NOT work at all with Python 3. The mbed deploy command at least fails on line 947 on mbed.py (the lamba stuff there seems to trick Python3).

Preferrably I'd like to see Python3 also being supported, but at least the documentation could be updated to mention that ONLY Python 2.7.x is supported.

**Comment by screamerbg** [comment]
It does starting from Mbed CLI 1.7.1. Note that this requires the latest Mbed OS (5.9)
