### ISSUE TITLE
Should be a link to information regarding profiles

### ISSUE THREAD

**Issue by adbridge** [ARMmbed/mbed-cli#387]
There is a command line option to specify a profile file. There is no information however about the profiles. There should at least be a comment along the lines of : 
"For more information about profiles , see . . . . . " and point to the docs in mbed-os

**Comment by adbridge** [comment]
https://github.com/ARMmbed/mbed-os/blob/master/docs/Toolchain_Profiles.md

**Comment by bridadan** [comment]
It might be too long to include the link from above, but you could say something along the lines of "Please see the mbed OS documentation for more details" on the command line, and provide a link to the actual doc in the mbed-cli README.

If that makes sense to you, would you be able to add that?

**Comment by screamerbg** [comment]
Now implemented. Thanks @adbridge !
