### ISSUE TITLE
Documentation improvement: Setting toolchain in osx for armgcc and other stuff

### ISSUE THREAD

**Issue by shayo** [ARMmbed/mbed-cli#392]
This is a documentation issue.
Can you please explain how do I set the toolchain in osx (you only mentioned for windows).
I'm using arm-none-eabi-gcc

Also, what is the proper target name for nrf51dk development board?

Thank you!

**Comment by bridadan** [comment]
@shayo The methods described in the README should work on OSX as well as Windows. We used Windows paths in the README but it should work with any type of path.

Also, if `arm-none-eabi-gcc` is in your shell's PATH, then it should be automatically detected with no need for any configuration!

> Also, what is the proper target name for nrf51dk development board?

`NRF51_DK` :)

**Comment by shayo** [comment]
Gotcha. I managed to run the compile. Now I get a crash. I'll open another issue.
