### ISSUE TITLE
'mbed export' without arguments should fail with error message

### ISSUE THREAD

**Issue by janjongboom** [ARMmbed/mbed-cli#410]
Run: `mbed export` on a project with a target set. This runs to completion but does not seem to have done anything...

Should show an error telling the user to select the `-i` flag.

**Comment by bridadan** [comment]
Good catch, this is definitely a problem!

I've issued a patch to mbed OS to clean up some of the arguments over there: https://github.com/ARMmbed/mbed-os/pull/3537

And I've also submitted a patch to mbed CLI to require the `-i` flag: https://github.com/ARMmbed/mbed-cli/pull/412

@janjongboom could you please review #412?
