### ISSUE TITLE
no forum identified on https://github.com/ARMmbed/mbed-cli

### ISSUE THREAD

**Issue by jahess** [ARMmbed/mbed-cli#414]
There is no forum identified on main git hub page for newbies to ask questions unworthy of being "an issue."

**Comment by jahess** [comment]
Meaning the main git hub page for mbed-cli.

**Comment by bridadan** [comment]
@jahess I believe the developer site (http://developer.mbed.org) would be what you're looking for, and that's listed at the top of the repo. But would you like to see this added to the README?

**Comment by screamerbg** [comment]
@jahess Bump

**Comment by theotherjimmy** [comment]
Closing from inactivity
