### ISSUE TITLE
mbed export --help does not enumerate export targets for -i

### ISSUE THREAD

**Issue by jahess** [ARMmbed/mbed-cli#415]
Yet, mis-specifying an IDE presents the list of possibilities.

**Comment by bridadan** [comment]
@jahess The error reporting could be better here, I agree. FYI, you can view the matrix of supported export IDEs and targets with `mbed export --supported`.

**Comment by awneil** [comment]
Where is the `mbed export --supported` option documented?

https://github.com/ARMmbed/mbed-cli#exporting-to-desktop-ides

Just says,

> mbed CLI supports exporting to Keil uVision, IAR Workbench, a Makefile using GCC ARM, Eclipse using GCC ARM and other IDEs.

Which is not very helpful or informative

**Comment by screamerbg** [comment]
@jahess Is this still an issue?
