### ISSUE TITLE
mbed export -i kds (TARGET K64F) results in non-functioning project

### ISSUE THREAD

**Issue by jahess** [ARMmbed/mbed-cli#417]
Using KDS 3.2 with KSDK 2.1 installed:

mbed import https://github.com/ARMmbed/mbed-os-example-blinky blinky_k64f_kds
cd blinky_k64f_kds
mbed config TARGET K64F
mbed export -i kds

Results in a dysfunctional kds project.  It appears code for all targets are included.

**Comment by 0xc0170** [comment]
cc @theotherjimmy @sarahmarshy

**Comment by theotherjimmy** [comment]
@jahess Revisiting the KDS exporter is on my todo list. Thanks for reporting a simple, easily reproduce-able exmaple.

**Comment by screamerbg** [comment]
@theotherjimmy @jahess Is this still an issue?

**Comment by theotherjimmy** [comment]
Yes

**Comment by screamerbg** [comment]
@theotherjimmy Bump
