### ISSUE TITLE
Empty project exported to SW4STM32

### ISSUE THREAD

**Issue by abouillot** [ARMmbed/mbed-cli#420]
When I export a mbed-cli project to SW4STM32 IDE, the project doesn't include any code.

I've tried opening it from the `.cproj` file or import it with the import option, using the `Existing Project into Workspace` or `Existing Code as Makefile Project`.

The project contains `Includes` folder, `mbed_config.h`, `exporter.yaml`, `GettingStarted.htm` and `Makefile`.

Similar operation to IAR  IDE works fine.

**Comment by 0xc0170** [comment]
cc @theotherjimmy @bcostm

**Comment by theotherjimmy** [comment]
@abouillot Could you try exporting to eclipse_gcc_arm? It should work for you. The SW4STM32 exporter is currently broken, and it's on my todo list to fix it.

**Comment by abouillot** [comment]
eclipse_gcc_arm isn't a recognized toolchain by mbed-cli.

**Comment by theotherjimmy** [comment]
how about `mbed export -i eclipse_gcc_arm -m ` your target?

**Comment by abouillot** [comment]
Here is the output:

```
F:\mbed-cli\mbed-programs\Nucleo_printf_test>mbed --version
1.0.0

F:\mbed-cli\mbed-programs\Nucleo_printf_test>mbed export -i eclipse_gcc_arm -m NUCLEO_L152RE -c
usage: project.py [-h] [-m MCU] [-i IDE] [-c] [-p PROGRAM] [-n PROGRAM] [-b]
                  [-L] [-S] [-E] [--source SOURCE_DIR] [-D MACROS]
project.py: error: argument -i: eclipse_gcc_arm is not a supported toolchain. Supported toolchains are:
atmelstudio,  coide,        ds5_5,        e2studio,     emblocks,
gcc_arm,      iar,          kds,          lpcxpresso,   simplicityv3,
sw4stm32,     uvision,      uvision4,     uvision5
[mbed] ERROR: "python" returned error code 2.
[mbed] ERROR: Command "python -u F:\mbed-cli\mbed-programs\Nucleo_printf_test\.temp\tools\project.py -i eclipse_gcc_arm -m NUCLEO_L152RE -c --source ." in "F:\mbed-cli\mbed-programs\Nucleo_printf_test"
---
```

**Comment by theotherjimmy** [comment]
Alright. Is this an mbed 2 project?

**Comment by theotherjimmy** [comment]
Or is your mbed-os pretty back-dated?

**Comment by abouillot** [comment]
you can find the code @ https://developer.mbed.org/users/abouillot/code/Nucleo_printf_test/ . This project has been created less than a week ago, I don't think any part of it is so outdated.

**Comment by theotherjimmy** [comment]
I don't have access to that repo.

**Comment by abouillot** [comment]
I change the repo to public.

**Comment by theotherjimmy** [comment]
So, mbed-dev uses the tools from here: https://developer.mbed.org/users/mbed_official/code/mbed-sdk-tools/
I have opened a PR to update the tools here: https://developer.mbed.org/users/mbed_official/code/mbed-sdk-tools/pull-request/1

When I get that PR merged, you can then start using the generic makefile-based eclipse exporters.

**Comment by screamerbg** [comment]
@theotherjimmy @abouillot Is this still an issue?

**Comment by theotherjimmy** [comment]
@abouillot The workaround (using `make_gcc_arm` or `eclipse_gcc_arm`) should now be possible. Could you try them out?

**Comment by screamerbg** [comment]
@abouillot @theotherjimmy bump
