### ISSUE TITLE
Projects are exported as Unnamed_Project

### ISSUE THREAD

**Issue by abouillot** [ARMmbed/mbed-cli#421]
When exporting to SW4STM or IAR IDEs, the projects are called Unnamed_project. This make working on different projects in parallel complex.

**Comment by screamerbg** [comment]
cc @theotherjimmy @sarahmarshy @0xc0170

**Comment by theotherjimmy** [comment]
@abouillot I cannot reproduce your problem with the latests version of mbed-os. Could you tell me which version of mbed-os you are using? or if you are using a version of mbed what the release number is?

**Comment by abouillot** [comment]
I'm using mbed-cli v1.0.0.

```
F:\mbed-cli\mbed-programs\Nucleo_printf_test>mbed export -i sw4stm32 -m NUCLEO_L152RE -c
Scan: lib
Scan: src
Scan: .

Successful:
  * NUCLEO_L152RE::sw4stm32     .\projectfiles\sw4stm32_NUCLEO_L152RE\Unnamed_Project

F:\mbed-cli\mbed-programs\Nucleo_printf_test>mbed --version
1.0.0
```

**Comment by theotherjimmy** [comment]
@abouillot Sorry for the confusion, I was asking for the version of mbed-os, not mbed-cli. Is the program you are using published somewhere?

**Comment by abouillot** [comment]
Code can be found @ https://developer.mbed.org/users/abouillot/code/Nucleo_printf_test/ , but there is nothing special about it.

**Comment by theotherjimmy** [comment]
So I don't have access to that repo... do you have an `mbed.bld` or a `mbed-os.lib` in the project's root directory?

**Comment by bridadan** [comment]
You can also run `mbed ls` and post the output here. That will give a recursive log of all libraries' commit hashes.

**Comment by abouillot** [comment]
I have mbed-dev.lib at the root

**Comment by screamerbg** [comment]
@adustm Could you please update your Mbed CLI to the latest version (1.7.1) and then run the following commands
```
cd <to your program>
cd mbed
mbed update # this will update the mbed library
cd ..
mbed export -i sw4stm32 -m NUCLEO_L152RE -c
```

Please let me know if that fixes your problem

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-465

**Comment by 0xc0170** [comment]
I tested this locally with 5.8.6, can't reproduce anymore. I'll close this issue as resolved
