### ISSUE TITLE
mbed remove doesnt work without first mbed deploy

### ISSUE THREAD

**Issue by mbartling** [ARMmbed/mbed-cli#422]
I have an mbed2 project I just imported from mercurial that I am porting to mbed OS 5, and when I run the following commands I get an error `[mbed] ERROR: Could not find library in path (mbed)`

```
mbed target K64F
mbed toolchain GCC_ARM
mbed remove mbed
mbed add mbed-os
mbed deploy
```

However this works

```
mbed target K64F
mbed toolchain GCC_ARM
mbed deploy                        #<=== Moved 
mbed remove mbed
mbed add mbed-os
```

**Comment by bridadan** [comment]
@mbartling Can you post the link to the mercurial repo? And can post the exact command you used to import the repo?

**Comment by screamerbg** [comment]
@mbartling bump

**Comment by mbartling** [comment]
No longer having this issue. Just checked with all of my mbed 2 examples
