### ISSUE TITLE
mbed-cli allows using hashless libs

### ISSUE THREAD

**Issue by teetak01** [ARMmbed/mbed-cli#424]
I noticed that I can remove the #HASH completely from .lib file. If this is then also pushed to github, mbed deploy will always pull in from head of master.

Just wondering that is this working as designed or possibly a bug in how mbed-cli handles .lib files. Considering relation to this issue: https://github.com/ARMmbed/mbed-cli/issues/224

**Comment by bridadan** [comment]
@teetak01 I believe the functionality should be that if there is no #HASH, it would pull from master and then save the .lib with the #HASH from the tip of master. Is this the behavior you're seeing?

**Comment by teetak01** [comment]
Yes, that is what I'm observing. mbed-cli was earlier pretty strict about .lib file usage so was wondering correctly. The current functionality is fine for me.

**Comment by bridadan** [comment]
> The current functionality is fine for me.

I think so too. I'll close this then, thanks for raising your concern!
