### ISSUE TITLE
Error when using 'mbed new .' on exported Online project

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/mbed-cli#429]
Reproduce with these steps:

1. Download ZIP file from existing online project:
https://developer.mbed.org/teams/mbed-os-examples/code/mbed-os-example-blinky/export

2. Unzip and change to directory

3. dir /A

```
29/01/2017  15:10                32 .gitignore
29/01/2017  15:10    <DIR>          .hg
29/01/2017  15:10    <DIR>          img
29/01/2017  15:10               213 main.cpp
29/01/2017  15:12    <DIR>          mbed-os
29/01/2017  15:10                77 mbed-os.lib
29/01/2017  15:10             2,737 README.md
```

4. `mbed new .`

Output:
```
[mbed] ERROR: A repository already exists in "C:\mbed\xxx\mbed-os-example-blinky_zip_NUCLEO_F429ZI\mbed-os-example-blinky" based on git. Please select a different name or location.
---
```

5. `mbed compile`

```
[mbed] WARNING: Could not find mbed program in current path "C:\mbed\xxx\mbed-os-example-blinky_zip_NUCLEO_F429ZI\mbed-os-example-blinky".
[mbed] WARNING: You can fix this by calling "mbed new ." in the root of your program.
...
```

Either the exported should not have a `.gitignore` directory, or mbed CLI should be able to handle this.

**Comment by bridadan** [comment]
Hey marcelo, I'm not sure if that's quite the correct command to use (though I think the behavior could be modified to be smarter about this).

Can you try `mbed deploy` instead of `mbed new .`?

**Comment by bridadan** [comment]
@MarceloSalazar sorry didn't realize the code was already there!

Ok, so pretty sure this is related to https://github.com/ARMmbed/mbed-cli/pull/397.

If you create a `.mbed` file then mbed-cli stops complaining. I think `mbed new .` should probably be smart enough to realize that it's already a project and just add the `.mbed` file. @screamerbg what do you think?

**Comment by bridadan** [comment]
Also side note @MarceloSalazar, any reason you're not using `mbed import` instead of the zip exporters?

```
mbed import https://developer.mbed.org/teams/mbed-os-examples/code/mbed-os-example-blinky
```

I agree the exporters should work as well (and mbed CLI should be smart enough to cope with them), but it seems a lot less complicated to just run the command above. You shouldn't have this same problem then.

**Comment by MarceloSalazar** [comment]
Using `mbed import` and then `mbed export ...` is a workaround.
It would be nice to fix the `mbed new .` to add the `.mbed` file.

**Comment by screamerbg** [comment]
@theotherjimmy Can we make the online exporters to create .mbed file in the root of the program containing `ROOT=.` for when exporting a repository (e.g. .hg/.git inside?)

**Comment by theotherjimmy** [comment]
Yes. That's should be a quick change.

**Comment by screamerbg** [comment]
@MarceloSalazar @theotherjimmy Any progress on this?

**Comment by theotherjimmy** [comment]
Putting up the patch now.

**Comment by theotherjimmy** [comment]
https://github.com/ARMmbed/mbed-os/pull/4224

**Comment by theotherjimmy** [comment]
Alright: Now we have to update the tools in the website... I'll keep you posted.

**Comment by screamerbg** [comment]
@theotherjimmy bump

**Comment by theotherjimmy** [comment]
Currently available on the website. Closing.
