### ISSUE TITLE
mbed sync ignores forks of mbed-os / sets lib reference incorrectly

### ISSUE THREAD

**Issue by maclobdell** [ARMmbed/mbed-cli#430]
While testing an application example using a fork of mbed OS (from a PR), I wanted to sync the mbed-os library to the mbed-os fork instead of the main repo location. 

However, mbed sync seems to always assume that mbed-os is located at https://github.com/armmbed/mbed-os/

Steps to recreate: 

mbed import mbed-os-example-mesh-minimal
cd mbed-os-example-mesh-minimal\mbed-os
git remote add myremote https://github.com/pradeep-gr/mbed-os5-onsemi
git fetch myremote
git checkout myremote/master
cd ..
mbed sync

This results in mbed-os.lib containing an invalid reference to: 
https://github.com/ARMmbed/mbed-os/#079aedf2531e23a504b5f1ca761ec87033792f0f
which does not exist. 
It should be:
https://github.com/pradeep-gr/mbed-os5-onsemi/079aedf2531e23a504b5f1ca761ec87033792f0f

**Comment by screamerbg** [comment]
@maclobdell We should add some documentation to point out that Mbed CLI "prefers" `origin` remote and therefore you should change the "origin" URL if you're pulling from a fork. Is this something you could look at with perhaps @AnotherButler ?

**Comment by maclobdell** [comment]
ah, I see.  I thought that it could figure out which remote you want to specify based on if you have a specific remote/branch checked out, but I guess that isn't possible.   I agree this would be good to document.  Perhaps also this could be mentioned in the help for mbed sync (mbed sync -h).

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-464

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
