### ISSUE TITLE
mbed-cli downloads mbed 2.0 tools during library updates

### ISSUE THREAD

**Issue by bremoran** [ARMmbed/mbed-cli#432]
When I use mbed-cli to update a single library in my tree for testing/development, it downloads redundant copies of the mbed 2.0 build tools.

mbed-cli should not download the mbed 2.0 build tools when it is inside a mbed OS 5.0 library, which is in a mbed OS 5.0 application.

**Comment by bridadan** [comment]
Hi @bremoran, could you provide the following:

1. Your mbed CLI version `mbed --version`
2. The commands we can use to reproduce this issue.

Thanks!

**Comment by bremoran** [comment]
```
$ mbed --version
1.0.0
```

Suppose we have an mbed OS 5 application: app. It uses a library: lib. We want to change lib to a new branch: branch.

1. `git clone http://domain.name/path/to/app.git`
2. `cd app`
3. `mbed deploy`
4. `cd lib`
5. `mbed update branch`

mbed will report:
```
[mbed] Couldn't find build tools in your program. Downloading the mbed 2.0 SDK tools...
```

**Comment by bridadan** [comment]
@bremoran I wasn't able to reproduce your issue. I'm using mbed CLI 1.0.0 on Windows 7. Here are the commands I ran. Can you reproduce the error on your machine with the following?

```
git clone https://github.com/ARMmbed/mbed-os-example-mesh-minimal
cd mbed-os-example-mesh-minimal
mbed deploy
cd atmel-rf-driver
mbed update retries
```

`retries` was just a random branch I found the atmel-rf-driver repo.

**Comment by screamerbg** [comment]
@bremoran Could you provide more details for us to reproduce?

**Comment by screamerbg** [comment]
Closing as there is no instructions to reproduce. Please reopen if needed.
