### ISSUE TITLE
mbed update has unexpected behaviour with caching enabled

### ISSUE THREAD

**Issue by bremoran** [ARMmbed/mbed-cli#440]
I have some config set:
```
$ mbed config -L
[mbed] Global config:
CACHE=/var/mbed
PROTOCOL=ssh
```

If I pick a project I have used before, that has had numerous commits since the last time I used it, and do `mbed import`, mbed correctly imports from the cache.

This means that when I do `mbed update master`, mbed does fetch the remotes correctly, but it doesn't update the local branches, so master is the master that was in use when the cache was populated.

If caching were turned off, this behaviour would be completely different, fetching the tip of master, from when I did the import.

**Comment by screamerbg** [comment]
@bremoran Thanks for the bug report. Can you please try PR #462?

**Comment by screamerbg** [comment]
@bremoran Bump :)

**Comment by screamerbg** [comment]
@bremoran could you please try to reproduce with mbed CLI v1.1 (latest) ?
