### ISSUE TITLE
[OOB_5_4] Windows installer shows unknown publisher

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/mbed-cli#444]
- Windows 10, fresh PC.
- mbed CLI Windows Installer v0.33

<img width="510" alt="mbed-cli-installer-unknown-publisher" src="https://cloud.githubusercontent.com/assets/1931553/23411480/512743a2-fdca-11e6-9c5a-e8b036ef43d6.png">

**Comment by screamerbg** [comment]
@arekzaluski Could you please look whether this is still an outstanding issue?

**Comment by MarceloSalazar** [comment]
Issue still shown in mbed CLI v0.3.6-alpha

**Comment by ashok-rao** [comment]
Looks like fixed in v0.4.0. More details are here: https://jira.arm.com/browse/IOTTOO-2518 .. Still needs to be tested :-)

**Comment by screamerbg** [comment]
Closing as it seems to be fixed. Please reopen if reoccurs.
