### ISSUE TITLE
[OOB_5_4] Windows uninstaller leaves environmental variables

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/mbed-cli#445]
- Windows 10, fresh PC. Installed mbed CLI succesfully. Then uninstalled.
- mbed CLI Windows Installer v0.33

There are environmental variables left after completion of uninstall.

<img width="442" alt="environmental-variables" src="https://cloud.githubusercontent.com/assets/1931553/23415047/de0898d8-fdd5-11e6-809e-a0e145573f04.PNG">

<img width="479" alt="system-variables" src="https://cloud.githubusercontent.com/assets/1931553/23415288/b3afb778-fdd6-11e6-8115-babf9e137455.PNG">

**Comment by screamerbg** [comment]
@arekzaluski Could you please look whether this is still an outstanding issue?

**Comment by MarceloSalazar** [comment]
This issue is no longer valid. Testing new behaviour in v0.3.6
