### ISSUE TITLE
[OOB_5_4] Windows installer cannot install mbed.py

### ISSUE THREAD

**Issue by soramame21** [ARMmbed/mbed-cli#446]
regarding **Test 3**, when I run mbed_installer_v033_cli_v100.exe and got following popup. I just want to skip Python installation, but mbed.py cannot be installed.
Is it a expected behavior?

![nombed_installed](https://cloud.githubusercontent.com/assets/17120422/23448019/f7332154-fe91-11e6-8548-6caa77cfc99b.png)

**Comment by soramame21** [comment]
@arekzaluski @MarceloSalazar Could you verify this issue and give your comment?

**Comment by arekzaluski** [comment]
What version of python did you have installed? Was it 2.7+ or 3+? It should skip only python installation. Currently this check is checking only if python is installed on the system (no matter what version) and I believe that mbed-cli is compatible only with python 2.7+. I extended this check in new build version of installer.

**Comment by soramame21** [comment]
@arekzaluski I pre-installed python 2.7 under C:\Program Files (x86) not the directory C:\Python27.

**Comment by arekzaluski** [comment]
Thanks, I'll investigate it.

**Comment by screamerbg** [comment]
@soramame21 Can you try with the latest installer please?

**Comment by soramame21** [comment]
@screamerbg, Sorry for such delayed reply. the windows installer is verified and works well. I will close this issue.

**Comment by soramame21** [comment]
I tested on Windows 10 environment.
