### ISSUE TITLE
mbed target lists different in make.py and project.py

### ISSUE THREAD

**Issue by mbartling** [ARMmbed/mbed-cli#459]
Hey,

The matrices generated by `mbed compile --supported` and `mbed export --supported` have different lists of targets.

**Comment by screamerbg** [comment]
Please file this against https://github.com/ARMmbed/mbed-os

**Comment by bridadan** [comment]
FYI, `mbed compile --supported` by default only shows mbed OS 5 targets. I'm guessing `mbed export --supported` shows mbed 2 targets as well.

**Comment by mbartling** [comment]
@bridadan I thought `mbed compile` picked targets based on the current project mbed OS version?

**Comment by bridadan** [comment]
The tools aren't aware of the OS version, so nope!
