### ISSUE TITLE
mbed-cli leaks compiler process in CI

### ISSUE THREAD

**Issue by mazimkhan** [ARMmbed/mbed-cli#479]
Please see the screenshots:
![mbed-cli-process-leak1](https://cloud.githubusercontent.com/assets/13520658/25285552/854cc402-26b2-11e7-93d8-cc7b4b4bde57.png)
![mbed-cli-process-leak2](https://cloud.githubusercontent.com/assets/13520658/25285553/8553f3da-26b2-11e7-9920-45fa1b4b3c1e.png)

Suspended/Zombi ```arm-none-eabi-g++.exe``` prevent recursive deletion of workspace. Causing subsequent builds to fail.

**Comment by theotherjimmy** [comment]
This is a problem with the tools in mbed-os. Please re-open there.

**Comment by theotherjimmy** [comment]
Further, it should not be a problem if you have an init process that reaps orphaned children.

**Comment by mazimkhan** [comment]
I would not want to pollute CI jobs with cleaning up of orphaned processes. Unless there is a slick Jenkins plugin that does this reliably.
It would be better at least maintained apps like build tools don't leak processes.

**Comment by mazimkhan** [comment]
Created https://github.com/ARMmbed/mbed-os/issues/4213

**Comment by jupe** [comment]
CC: @miklis @marhil01

**Comment by screamerbg** [comment]
This is now tracked in https://github.com/ARMmbed/mbed-os/issues/4213. Closing here
