### ISSUE TITLE
Duplicate optimization settings on IAR EWARM export

### ISSUE THREAD

**Issue by ASealion** [ARMmbed/mbed-cli#487]
tested on 7.7 and 8.11

**Steps to reproduce**
After exporting a project from the online compiler is is not possible to compile the project. 
Since the project options on the "Optimizer" are set to "High" and there is a extra Option "-Oh".

This leads to the compiler message:
[Su004]: Option -O can only occur once

**Comment by 0xc0170** [comment]
cc @theotherjimmy

**Comment by theotherjimmy** [comment]
Whoops. Thanks for finding this. The python that is run when you export is here: https://github.com/ARMmbed/mbed-os/tree/master/tools/export/iar This may not be the only duplicate option. You are welcome to submit a PR to mbed-os @ASealion. I can help out, or make the PR.

**Comment by theotherjimmy** [comment]
Good call on the labels @screamerbg.

I'm going to take a look today, @ASealion. I'll mention the PR I create here.

**Comment by theotherjimmy** [comment]
Looks like [this line](https://github.com/ARMmbed/mbed-os/blob/master/tools/export/iar/__init__.py#L117) needs to check for `-Oh`

**Comment by theotherjimmy** [comment]
See https://github.com/ARMmbed/mbed-os/pull/4293 for the fix

**Comment by Val-Apana** [comment]
In IAR: Project -> Options-> C/C++ Compiler: “Extra Options” tab, scroll down and delete the “-Oh” line.

**Comment by theotherjimmy** [comment]
Yup. That's what the PR I mentioned prevents you from having to do.
