### ISSUE TITLE
"mbed compile -v' fails on Unicode error when printing out warning

### ISSUE THREAD

**Issue by teetak01** [ARMmbed/mbed-cli#488]
How to reproduce:

tested with mbed-cli 1.1.1

Example program.
```
#include "mbed.h"
#include <stdio.h>

main ()
{
    printf("Fail!\ŋ");
}
```

```
mbed import mbed-os
mbed compile -v
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 35: ordinal not in range(128)
```

So the mbed-cli is in fact failing because it cannot print out the warning message correctly. That code compiles (with warning) fine with `mbed compile`

Of course that line is typoed bug, but the verbosity mode itself probably should not terminate compilation.

**Comment by theotherjimmy** [comment]
Hi @teetak01,

I'm pretty sure that this is an error with the tools that reside in the mbed-os repo. Could you raise the issue there?
