### ISSUE TITLE
Allow setting the name of the application

### ISSUE THREAD

**Issue by janjongboom** [ARMmbed/mbed-cli#493]
If I have a project with both firmware and a web app I put the firmware in a 'firmware' folder. Now my program is called 'firmware'. I want to be able to set the program name somewhere (maybe .mbed file).

**Comment by bridadan** [comment]
@janjongboom The `mbed compile` command supports the `--artifact-name` option which lets you set the name of the binary created. Does this serve your purpose?

**Comment by theotherjimmy** [comment]
Further, recent version of mbed-os support the `artifact_name` key in mbed_app.json, as an alternative to the command line switch.

**Comment by janjongboom** [comment]
@theotherjimmy @bridadan Cool!
