### ISSUE TITLE
mbed-os-example-blinky breaks on NRF52_DK when NDEBUG macro set

### ISSUE THREAD

**Issue by saedelman** [ARMmbed/mbed-cli#502]
Both online compiler (using Compile Macros -> NDEBUG) and MBED-CLI (mbed_app.json) causes application freeze in blinky with NRF52_DK as target. I have not tested it for other targets.

**Comment by bridadan** [comment]
@saedelman Thanks for reporting this. Could you please report this at https://github.com/ARMmbed/mbed-os? Could also include the version of mbed-os or the commit hash of the blinky example you're using when you report it there? Thanks!

**Comment by screamerbg** [comment]
@saedelman I think this is a linked issue https://github.com/ARMmbed/mbed-os/issues/2467. As @bridadan suggested, please raise an issue against https://github.com/ARMmbed/mbed-os so the Nordic engineering team have visibility on this.

**Comment by saedelman** [comment]
@bridadan @screamerbg Done. https://github.com/ARMmbed/mbed-os/issues/4621

**Comment by bridadan** [comment]
Thanks!
