### ISSUE TITLE
Windows Uninstaller did not clean the relevant system path.

### ISSUE THREAD

**Issue by tz-arm** [ARMmbed/mbed-cli#506]
After ninstall mbed-cli using uninstaller and reboot the system, there is still some mbed-cli relevant paths in system environment.

**Comment by ashok-rao** [comment]
Hi @tz-arm , it's been updated in 0.4.0. Can you please re-download the installer and check again? My bad, I had not updated the download link for the installer..

**Comment by tz-arm** [comment]
verified that this has been fixed on v0.4.0.
