### ISSUE TITLE
Windows Uninstaller did not remove the git and mercurial which is installed by installer- enhancement

### ISSUE THREAD

**Issue by tz-arm** [ARMmbed/mbed-cli#507]
The uninstaller did not remove git & mercurial which is installed by installer, propose to add a remove checkbox in uninstaller too.

**Comment by theotherjimmy** [comment]
@arekzaluski Any news on this?

**Comment by arekzaluski** [comment]
@theotherjimmy @tz-arm There is a ticket to implement this behaviour. ETA is not known yet.

**Comment by theotherjimmy** [comment]
Thanks @arekzaluski. Could you keep this issue up to date? I would appreciate that.

**Comment by screamerbg** [comment]
@arekzaluski What's the status of this?

**Comment by arekzaluski** [comment]
@tz-arm @theotherjimmy @screamerbg This functionality has been implemented in newest version of installer : 0.5.1
Uninstaller removes now both github and mercurial if they were installed using installer.

**Comment by screamerbg** [comment]
@arekzaluski Thank you!
