### ISSUE TITLE
Windows Installer shows warning that “The verified publisher is unknown” - enhancement.

### ISSUE THREAD

**Issue by tz-arm** [ARMmbed/mbed-cli#509]
For both windows7 and windows10, there is warning message that "The verified publisher: unknown".
Apparently the user will consider that the software is not published officially.

**Comment by arekzaluski** [comment]
The problem was fixed in version 0.4.0 of installer. Is this problem relevant to version 0.4.0 or previous?

**Comment by tz-arm** [comment]
This issue has been found on v0.33 via https://github.com/ARMmbed/mbed-cli/tree/windows-installer.
Just got the new link of v0.4 and verified ok now.
