### ISSUE TITLE
Enhancement request: mbed upgrade or mbed update -f

### ISSUE THREAD

**Issue by RobMeades** [ARMmbed/mbed-cli#511]
See conversation over in #505, it is a complete pain trying to develop a set of libraries as there is no way to tell mbed to just update everything to latest.  I recognise that there are dangers in doing this but, when actively developing a suite of libraries, a developer is perfectly aware of any changes he/she has made and just wants everything to stay in sync with what's archived; the only way to do that is to jump through all the directories and update each one individually, which is just horrible, almost unworkable, especially when one has to do it in the right order to avoid elements higher in the try *downgrading* the ones below again.

Hence, I request a new feature, which could either be `mbed upgrade` or a `-f` (==force) switch to `mbed update`.  The effect of this would be to update all the libraries to their latest versions, re-writing the `.lib` files as it goes.  A warning could be provided, something like "All libraries will be update to their latest versions, which may introduce incompatibilities; are you sure you want to continue? (y/n)"

**Comment by bridadan** [comment]
How would you feel about `mbed update --recursive/-r` ?

**Comment by RobMeades** [comment]
Yes, like that, even more intuitive.

**Comment by bridadan** [comment]
@theotherjimmy @screamerbg Thoughts? Concerns?

**Comment by theotherjimmy** [comment]
Sounds like a good idea. Would be useful for developing libraries. I like the "default behavior that probably won't break something" and "turn on dangerous mode" duality. @screamerbg will probably want a warning.

**Comment by bridadan** [comment]
Feature request: `mbed config -G dangerous_mode enabled` 😛

**Comment by theotherjimmy** [comment]
@bridadan FTFY
>Feature request: `mbed config -G danger_zone enabled` 😛

**Comment by screamerbg** [comment]
@RobMeades @bridadan I like the feature request, and also that it doesn't impact the default behavior. The online IDE supports this via the Update All functionality already. 

Want to hear @sg- 's thoughts as well.

**Comment by sg-** [comment]
👍

**Comment by theotherjimmy** [comment]
@RobMeades It looks like your feature has approval. Did you plan on implementing it?

**Comment by RobMeades** [comment]
Ah, well, umm, I'd have to learn Python first...

**Comment by theotherjimmy** [comment]
@RobMeades No worries. I'll get on it soon. :wink:

**Comment by theotherjimmy** [comment]
I just tried some stuff here, the diff is _tiny_ (+3, -2). However, There is a limitation: You cannot update the repos that have a detached head state. my current implementation of `-r/--recursive` updates all repos that are _on a branch_ in the tree of the current project.

**Comment by RobMeades** [comment]
If I've understood detached head state properly, that might be the kind of situation where you'd really appreciate `mbed update -r`, as a sort of "get me to head" rescue.  I suppose it could warn the user and they'd have to go and do a manual `mbed update` in the directory instead?

**Comment by theotherjimmy** [comment]
@RobMeades When your dependency is in a detached head state, mbed CLI has no way to determine what branch you are on, so `mbed update -r` will do the same thing as `mbed update` for that one dependency. If, OTOH, you are not in a detached head state, it updates to the latest revision of the current tracking branch.

**Comment by theotherjimmy** [comment]
The reason we can't determine which branch you are on is simple. Let's talk about a repo with a single commit:
```
o - master
```
Now I create another branch with another commit on top:
```
o - new-branch
|
o - master
```
Now we do something very reasonable: we add a commit to master
```
o - new-branch o - master
|______________|
o
```
Now I check out the commit before master (the bottom commit in the diagram). Which branch am I behind now?

**Comment by RobMeades** [comment]
Understood.  I think it would be good for the user to know if `mbed update -r` was unable to update a `.lib` because it was in a detached HEAD state, basically print a message saying so, then they know it's going to be left behind and they can fix it manually.  That would be fine.

**Comment by theotherjimmy** [comment]
@RobMeades I'll look into making that happen.

**Comment by RobMeades** [comment]
Many thanks.

**Comment by theotherjimmy** [comment]
@RobMeades It's done. Check PR #512

**Comment by RobMeades** [comment]
Excellent, many thanks guys, I'll wait for it to get into a release and try it out.
