### ISSUE TITLE
Transcluded README means 5.4 docs have 5.5 information

### ISSUE THREAD

**Issue by AnotherButler** [ARMmbed/mbed-cli#519]
https://docs.mbed.com/docs/mbed-os-handbook/en/5.4/dev_tools/cli/#toolchain-selection says to use GCC 6 instead of GCC 4.9.3. This would be correct for 5.5, but this doc is for 5.4. I think this is because it's a transcluded page.

@iriark01 What's the best way to fix this for now?

**Comment by iriark01** [comment]
mbed CLI needs to have branches for old versions.

**Comment by AnotherButler** [comment]
@screamerbg Do you have branches available for older versions?

**Comment by screamerbg** [comment]
You can point to the tags

**Comment by AnotherButler** [comment]
@iriark01 Can you help me with this? My research so far has not been as productive as I would like.

**Comment by iriark01** [comment]
If you know which version of CLI maps to which version of Mbed OS, you can in theory transclude pages from the release: https://github.com/ARMmbed/mbed-cli/releases

**Comment by AnotherButler** [comment]
@iriark01 Thanks so much. :) We have now resolved this issue, so I am closing it. Please feel free to reopen if needed.
