### ISSUE TITLE
Compile build error with spaces in paths

### ISSUE THREAD

**Issue by noutram** [ARMmbed/mbed-cli#522]
On Windows 10, I justy tried to build some code (known to work) and it failed. It turned out the issue was with there being a space in the path on that particular user account.

I assume this is a known issue, but I thought I should flag it. Maybe I should generate a PR for the READ_ME?

**Comment by theotherjimmy** [comment]
Hey @noutram. We're fixing this issue. Let me get the PR number for you.

**Comment by theotherjimmy** [comment]
Resolved by https://github.com/ARMmbed/mbed-os/pull/4468

**Comment by theotherjimmy** [comment]
And merged :3

**Comment by theotherjimmy** [comment]
Would you like a comment in the README for older versions of mbed OS?

**Comment by noutram** [comment]
Might be an idea. It had me confused for quite a while (until, I confess, I read the error messages properly)
