### ISSUE TITLE
mbed installer and mbed serial driver problem

### ISSUE THREAD

**Issue by rspelta** [ARMmbed/mbed-cli#527]
Hello,
I'm using windows 7 and I tried to install mbed-cli using the installer named "mbed_installer_v041.exe"
When the installer tries to install the mbed serial driver I have already plugged to the PC the **ST NUCLEO_F429ZI** but it is not recognized from the installer:

![immagine](https://user-images.githubusercontent.com/3882627/28725277-43c4342c-73bd-11e7-9d37-1a65c854e160.png)

I resolved this issue installing manually the driver using the file **en.stsw-link009.zip** provided by ST website.

Is there some advice in order to avoid to install manually this driver?

Thanks

**Comment by bridadan** [comment]
@arekzaluski Do we have any plans to detect boards that are attached before installing the serial driver?

**Comment by arekzaluski** [comment]
@rspelta @bridadan I'm able to reproduce it. It seems that mbedWinSerial does not support Nucleo F429ZI board. I'll investigate it further and check what can be done to improve the process.

**Comment by rspelta** [comment]
Perfect, thank you!

**Comment by bcostm** [comment]
Same problem with me using another board (NUCLEO_F103RB).

The STLINK driver must be installed first:
[[https://my.st.com/content/my_st_com/en/products/embedded-software/development-tool-software/stsw-link009.license%3d1502449373926.html]]

But running the mbed_installer_v041.exe after STLink driver is installed does not change the behaviour: same error message as described by @rspelta

**Comment by screamerbg** [comment]
@arekzaluski please see above

**Comment by screamerbg** [comment]
@arekzaluski @rspelta Is this still an issue?

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-458
