### ISSUE TITLE
Add `mbed describe` functionality

### ISSUE THREAD

**Issue by seppestas** [ARMmbed/mbed-cli#534]
When developing firmware that can be programmed using DFU it is very helpful to know the exact version and state of the firmware that is programmed on a device / compiled in a DFU package.

For this, I typically use the [`git describe --tags --match "v*" --dirty` command](https://git-scm.com/docs/git-describe), which will just output the version tag if the last commit was tagged with a version (useful for "production" releases), but also the amount of commits since the last tag, the last commit hash and whether files in the repository where changed since the last commit (super useful during development).

However, since mbed libraries are ignored by git, changes to files in mbed libraries do not get reflected by `git describe`. `mbed status` can show changed files in libraries, but it does not give any information if a different revision of a library is checked out than what is defined in the .lib file. Also, for some reason `mbed status` does not show changes to files in the main repository.

An `mbed describe` command with similar options to `git describe` would be a very helpful feature to solve this problem.

Alternatively, having `mbed status` show "out of sync" libraries or having a "dry-run" option to `mbed deploy` would allow to build up a complete state description using the existing commands.

Having the `mbed describe` command would have the big benefit of supporting Mercurial repositories and it would make it possible to easily ignore files outside of the scope of the firmware but still checked into the repository (we typically put the mbed-based firmware and PCB design files in the same repo, but there is no point in flagging the firmware as dirty if a change was made to e.g the PCB layout).

**Comment by adbridge** [comment]
*Issue header has missing or incorrectly filled in fields! Please fix.*
