### ISSUE TITLE
CLI uses hard-coded binary to invoke project.py

### ISSUE THREAD

**Issue by chrylis** [ARMmbed/mbed-cli#550]
At line 2407, `mbed.py` uses a hard-coded exec call to `'python'` to invoke `project.py`. As `python` is generally Python 3 on modern systems, this tends to break with syntax errors.

At line 2423, it uses `python_cmd`, which is presumably sane, and this is probably the right approach (barring an update of the whole CLI to Python 3, of course). Note that this idiom occurs elsewhere, such as at 2195.

**Comment by screamerbg** [comment]
@chrylis Thanks for the report. You're right, these should be unified.

**Comment by screamerbg** [comment]
@chrylis Implemented, merged and now available in Mbed CLI 1.2.2.
