### ISSUE TITLE
How can I change my platform

### ISSUE THREAD

**Issue by RozenAstrayChen** [ARMmbed/mbed-cli#553]
If I need change my platform like``` LPC1768``` -> ```NUCLEO_F401RE``` , how can i do?

**Comment by bridadan** [comment]
You can use the `-m` option to change your platform or you can set it with the `mbed target` command:

```
mbed compile -m NUCLEO_F401RE
```

OR

```
mbed target NUCLEO_F401RE
mbed compile
```

**Comment by theotherjimmy** [comment]
Please reopen if you need more assistance
