### ISSUE TITLE
question about "--no-archive"

### ISSUE THREAD

**Issue by tz-arm** [ARMmbed/mbed-cli#559]
Seems there is no explanation and no help comments for the parameter of "--no-archive"
Is it relevant to gcc "--no-whole-archive"?

**Comment by theotherjimmy** [comment]
> Is it relevant to gcc "--no-whole-archive"?

I don't think so

That option is used in conjunction with `--library` to build a bunch of C/C++/ASM files as a static library. The `--no-archive` flag suppresses the creation of the `.a` file, and the deletion of the intermediate `.o` files.

**Comment by theotherjimmy** [comment]
Marked as documentation, as there is no explanation of the command line option mentioned in this issue.

**Comment by screamerbg** [comment]
@AnotherButler Could you please discuss with @theotherjimmy what's the right explanation/terminology for the `--no-archive` option?

**Comment by theotherjimmy** [comment]
@screamerbg @AnotherButler I think I did this a while back: https://github.com/ARMmbed/Handbook/pull/394

@tz-arm Does the current documentation answer your question?

**Comment by adbridge** [comment]
*Issue header has missing or incorrectly filled in fields! Please fix.*
