### ISSUE TITLE
Progress bar when importing

### ISSUE THREAD

**Issue by janjongboom** [ARMmbed/mbed-cli#562]
Could we show some progress while importing? Maybe just normal git progress?

Currently we give no clue to a user how far the import process is.

**Comment by theotherjimmy** [comment]
Marked as "help wanted" because I'm bogged down in other things right now.

**Comment by MarceloSalazar** [comment]
Feature already requested: https://github.com/ARMmbed/mbed-cli/issues/136

**Comment by bridadan** [comment]
@janjongboom Should be straightforward enough, but like Jimmy said I'm loaded with other things at the moment.

If you run `mbed import` with the `-v` flag it will output the `git` command output, which includes the progress.

If that isn't good enough, we could look into maybe parsing the git output as its printed and just getting the progress info.

**Comment by screamerbg** [comment]
@janjongboom @bridadan @MarceloSalazar PR #593 introduces this.

**Comment by MarceloSalazar** [comment]
@screamerbg looks good, thanks!

**Comment by janjongboom** [comment]
@screamerbg Nice!

**Comment by screamerbg** [comment]
Now available in Mbed CLI 1.4.0
