### ISSUE TITLE
export multiple profiles as multiple build configurations

### ISSUE THREAD

**Issue by bmcdonnell-ionx** [ARMmbed/mbed-cli#588]
### Description

Can we add the ability to export multiple build profiles as multiple build configurations in a single IDE project.

Background:

Inspired by [C++11 in exported projects](https://os.mbed.com/questions/79757/C11-in-exported-projects/?c=29224).

In source control for my projects, I'm currently keeping just the files needed so that a developer can check out, and either build or export with mbed-cli. This is in keeping with the convention of publicly-available sample programs.

`mbed export` apparently creates multiple build configurations - one each for Debug and Release - at least it does for MCUXpresso. (`mbed export -m LPC4088 -i mcuxpresso`.) But AFAIK, there is no way to both customize build flags (e.g. `-std=gnu++11`), and have more than one build configurations in the exported project.

### Issue request type

[ ] Question 
[x] Enhancement 
[ ] Bug

**Comment by screamerbg** [comment]
cc @theotherjimmy

**Comment by screamerbg** [comment]
Bump @theotherjimmy

**Comment by theotherjimmy** [comment]
@bmcdonnell-ionx I have no plans to implement multiple profile support at this time.

**Comment by adbridge** [comment]
*Issue header has missing or incorrectly filled in fields! Please fix.*

**Comment by bmcdonnell-ionx** [comment]
> *Issue header has missing or incorrectly filled in fields! Please fix.*

@adbridge, what does that mean?

**Comment by adbridge** [comment]
@bmcdonnell-ionx We have recently added an issue pro-forma which requires a checkbox selection stating the type of issue, to be filled in. There is also a new automated script which checks this which has just been enabled. It looks like mbed-cli does not have that proforma currently and this issue was raised prior to that coming in. I will fix it :)

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
