### ISSUE TITLE
Near-total test failure on Windows

### ISSUE THREAD

**Issue by davidhyman** [ARMmbed/mbed-cli#600]
`=============== 3 failed, 7 passed, 30 error in 306.61 seconds ================`
A lot of them seem similar failures - for example:
```
fatal: unable to access 'https://c//users/username/appdata/local/temp/pytest-of-username/pytest-5/test_sync_update_move_git1_0/test3/': Couldn't resolve host 'c'
```

**Comment by theotherjimmy** [comment]
@davidhyman #606 should have fixed this for you.

**Comment by davidhyman** [comment]
thanks @theotherjimmy , wfm
