### ISSUE TITLE
test coverage

### ISSUE THREAD

**Issue by davidhyman** [ARMmbed/mbed-cli#602]
Coverage for mbed\mbed.py : 50%
1776 statements   979 run 797 missing 0 excluded 122 partial

This indicates that there is work to be done either reducing the complexity of the code, or adding more tests to cover existing functionality.

As a heuristic guide, tools such as [this](https://codeclimate.com/github/davidhyman/mbed-cli) can assist in indicating areas to focus on.

**Comment by theotherjimmy** [comment]
@davidhyman We use coverage + coveralls for the Mbed OS build tools, Mbed Greentea, Mbed Htrun and Mbed ls. You are welcome to set something similar up for Mbed CLI. Before changing any test code, I would first like to see what the coverage looks like.

**Comment by screamerbg** [comment]
@davidhyman There's a lot going on circleyml that doesn't seem to be taken into account in these stats, e.g.
* Importing with Git, Hg, Bld
* Updating to a specific version with Git, HG, Bld
* Setting up config variables, default target
* Listing of supported toolchains, targets for compile, export, etc.

Do you could look at translating some of these to py.test tests so they are accounted against the coverage statistics you mentioned?

**Comment by theotherjimmy** [comment]
@screamerbg after #608, We can use `coverage -m mbed` instead of `mbed` on the command line, and get the coverage info for those commands. That sounds like a bit less work.

**Comment by davidhyman** [comment]
Yes - in theory - it would be a matter of using `coverage run mbed ...`  in place of `mbed` (then `coverage combine` and some other invocations)
In practise it may be somewhat fiddly getting this going, if we're only able to debug through CircleCI.

**Comment by davidhyman** [comment]
converting them to a suite of pytest tests with subprocess calls could also work though, and provides a single entrypoint for all tests

**Comment by adbridge** [comment]
*Issue header has missing or incorrectly filled in fields! Please fix.*

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
