### ISSUE TITLE
Source file size

### ISSUE THREAD

**Issue by davidhyman** [ARMmbed/mbed-cli#603]
In my experience the size of the file makes it quite difficult to browse and work with, and is larger than usual for Python applications. With working tests and judicious application of namespacing it should be possible to split it up.

**Comment by screamerbg** [comment]
Not a requirement for now, but we can consider it in the future.

**Comment by adbridge** [comment]
*Issue header has missing or incorrectly filled in fields! Please fix.*

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
