### ISSUE TITLE
undocumented environment vulnerability: 'pip'

### ISSUE THREAD

**Issue by davidhyman** [ARMmbed/mbed-cli#605]
L1375:
```
import pip
...
pquery(['pip', 'install'
```
The validity of doing this should be documented, because as it stands, it appears wrong: 'pip' will invoke whatever executable has that name on the current system path. It may not be an executable from the same interpreter that is executing the current file. It may not work in environments where pip is not on the system path, or where the system path pip does not match the current interpreter's installation for any reason. This could cause a number of issues e.g. when using a python interpreter that is directly invoked from an absolute path, or when using virtual environments.

**Comment by screamerbg** [comment]
Let's use #604 to track this and other tools that mbed CLI executes
