### ISSUE TITLE
improve test speed

### ISSUE THREAD

**Issue by davidhyman** [ARMmbed/mbed-cli#607]
Local test runs currently take ~20 minutes - it would be easier to develop if they were faster.

**Comment by theotherjimmy** [comment]
@davidhyman There is always a trade off between speed and completeness. You are welcome to suggest enhancements for the speed, as long as they maintain (or improve) the completeness of the tests.

**Comment by screamerbg** [comment]
Some stuff was introduced to improve `py.test test` in Mbed CLI 1.5.0

**Comment by screamerbg** [comment]
The py.test tests have been reduced to about 1:30 minutes with the Mbed CLI 1.5.0 release. Hope that solves the issue. The extended tests that include importing of remote repositories, compile etc, take another 10 minutes, but could be executed separately and primarily exercise other Mbed OS tools like the build system, exporters, supported targets etc.
