### ISSUE TITLE
Installation instructions ask for sudo pip install

### ISSUE THREAD

**Issue by drewcassidy** [ARMmbed/mbed-cli#614]
The [installation instructions](https://os.mbed.com/docs/v5.6/tools/setup.html) for mbed-CLI ask the user to install using `pip`, and suggests using `sudo pip install mbed-cli` on macOS and Linux. According to [this stackoverflow answer](https://stackoverflow.com/a/33004920/7645957), doing this is incorrect and can cause problems on recent versions of macOS.

Instead, the instructions should recommend installing with `pip install mbed-cli --user`. This might be a problem since it requires adding the install location to `$PATH` (in my case: `~/Library/Python/2.7/bin`)

**Comment by davidhyman** [comment]
https://github.com/pypa/pipenv is current best practice. It somewhat depends on what the user wants to do with their environments, but I would suggest that if they are just aiming for the easiest standalone install, this would be best across the board.
We could document both methods, but I feel that could be confusing for new users - it would be fair to assume that someone that already had a custom environment or python setup that they wanted to use would know how to use plain old `pip` instead.

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-453
