### ISSUE TITLE
Should not do full rebuild when switching profiles

### ISSUE THREAD

**Issue by janjongboom** [ARMmbed/mbed-cli#615]
Right now when you switch profiles it'll trigger a full rebuild. That is very annoying, I'm switching quite often between debug and release builds to look at memory usage etc. Can we not do this?

Downside is that changing the paths to `BUILD/PLATFORM/GCC_ARM/PROFILE/` requires change in documentation.

cc @mark-edgeworth

**Comment by mark-edgeworth** [comment]
alternative might be to add '-profilename' to the end of either the platform or the compiler parts in the BUILD structure, although this feels a bit hacky.

**Comment by geky** [comment]
You could create a symbolic link for the old path every build. Would be a cheap way to keep the old paths working for a while. The symbolic links could be removed at a later timer (6.0?)

**Comment by janjongboom** [comment]
I don't know if Windows properly supports them.

**Comment by screamerbg** [comment]
cc @theotherjimmy

**Comment by theotherjimmy** [comment]
@janjongboom I don't think in re-builds assembly. I'll freely admit that is at best a 2% speedup. @geky is correct in pointing out that we would have to make the final artifact available as part of the `BUILD/<target>/<toolchain>/` directory. Maybe just copying them would be sufficient? I'm open to ideas on this one.

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-452

**Comment by bmcdonnell-ionx** [comment]
> we would have to make the final artifact available as part of the `BUILD/<target>/<toolchain>/` directory.

I think you would want to do something like

`BUILD/<target>/<toolchain>/<build-profile-name-without-json-extension>/`

as I intended to suggest on #700.

**Comment by bmcdonnell-ionx** [comment]
>> You could create a symbolic link...
>
> I don't know if Windows properly supports them.

Several (most?) versions of Windows require administrator rights to create symbolic links. I don't think you want to impose that requirement on your users. (Please don't.)

**Comment by janjongboom** [comment]
@bmcdonnell-ionx Yes, exactly same proposal.

**Comment by bmcdonnell-ionx** [comment]
#712 has been merged to `master`, though not released yet.

Should this issue be closed?

**Comment by theotherjimmy** [comment]
Yes.
