### ISSUE TITLE
Doxygen command

### ISSUE THREAD

**Issue by geky** [ARMmbed/mbed-cli#617]
Is there a way to generate doxygen with mbed CLI?

Like the testing and config commands, a doxygen command would be quite helpful to verify that new doxygen is sane.

cc @theotherjimmy, @dannybenor, @AnotherButler

**Comment by theotherjimmy** [comment]
Nope. We could add that though.

**Comment by screamerbg** [comment]
@sg- There are already doxyfiles inside Mbed OS that could be used as a default template for doxygen. What do you think?

**Comment by theotherjimmy** [comment]
@screamerbg @geky  See the [`cargo doc` documentation](https://www.mankier.com/1/cargo-doc) for an instance of prior work. @screamerbg @sg- and I would have to work out what is appropriate behavoir for a `doc` subcommand.

**Comment by adbridge** [comment]
*Issue header has missing or incorrectly filled in fields! Please fix.*

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
