### ISSUE TITLE
Question? Best venue for support?

### ISSUE THREAD

**Issue by g40** [ARMmbed/mbed-cli#619]
This is almost certainly the wrong place to ask but ..

I can build a basic `mbed-os-program` with `-t GCC_ARM -m RZ_A1H` and get a .bin file (nice BTW, thanks). The build system has correctly cloned mbed-os. However if I simply add `#include usbmouse.h` I get 

```
1[Fatal Error] main.cpp@2,22: USBMouse.h: No such file or directory
[ERROR] .\main.cpp:2:22: fatal error: USBMouse.h: No such file or directory
 #include "USBMouse.h"

```
This does work with the online compiler and the target board. But in this case the relevant headers and source are in are `...\mbed\test\mbed-os-program\mbed-os\features\unsupported\USBDevice\USBHID`. Does this mean no USB support in the offline version? Or am I missing something else? 

Thanks.

**Comment by screamerbg** [comment]
@g40 you can use
```
$ cd <root_of_your_program>
$ mbed compile --source . --source mbed-os\features\unsupported\USBDevice\
```

Let me know how it goes.

**Comment by g40** [comment]
Thank you. I realized immediately after posting that I was better off with `mbed add http://mbed.org/users/mbed_official/code/USBDevice/`

Sadly that compilation fails. I will investigate further. BTW is issues acceptable for questions?

TAIA.
