### ISSUE TITLE
parser for MBED_MEM_TRACE output

### ISSUE THREAD

**Issue by thinkberg** [ARMmbed/mbed-cli#630]
### Description
- Type: Enhancement
- Priority: Minor

----------------------------------------------------------------
## Enhancement

The current memtrace is a very nice feature, but rather hard to use. Since my forum post is now in moderation for a week, maybe you'd like to integrate my little script into the cli tooling itself?

https://github.com/thinkberg/mbed-memtrace-logger

It parses the MEM_TRACE output and displays allocated heap and +/- values in a more readable form to aid debugging, while keeping log functionality.

Leo.

**Comment by theotherjimmy** [comment]
@thinkberg You're welcome to submit a PR. I'm not sure mbed CLI would be the best place for this. @screamerbg Do you have any thoughts on that subject?

**Comment by thinkberg** [comment]
I remember something like `yotta debug` in the old system which could be helpful here too. An mbed client way to start openocd/jlink gdb server and maybe even log serial output in a file/pipe it through the the script I wrote if tracing is enabled. 

I didn't know which is the best part to submit something too, so I wanted to get some feedback. It felt more home in mbed-cli than in the mbed-os part.

**Comment by screamerbg** [comment]
@thinkberg I agree with @theotherjimmy that Mbed CLI might not be the best place for the parsing. Do you think that this could be something like an external tool or python module, something that Mbed CLI could call? Or perhaps be part of Mbed OS tools given that many tools inside the OS have knowledge about the target, ram/flash, regions, even flash algos, device IDs, etc.

**Comment by thinkberg** [comment]
Sure, could be an external module that can be called. My reasoning was that its important enough to be easily accessible. Right now, having a memory leak involves quite some searching and guessing. Even the stack/thread debug that I referenced in the repo was a lucky find. You almost always find outdates mbed docs, unfortunately. Even if it would be part of the docs with reference to the external tools would be most helpful.

**Comment by screamerbg** [comment]
@thinkberg @theotherjimmy Mbed CLI now has a serial terminal feature (#664). Perhaps this is something that could be added to the serial terminal hooks and enable runtime memtrace functionality? Note that Mbed CLI does not have any external python dependencies, so the pygtail dependency should be somehow workarounded.

**Comment by thinkberg** [comment]
Actually, pygtail was just a workaround due to buffering issues. If the mbed cli serial can pipe its data into a stream it would be simple to make it work.

**Comment by thinkberg** [comment]
If you give me a hint where to integrate (where are the serial terminal hooks?), I can port it to be part of the cli.

**Comment by theotherjimmy** [comment]
@thinkberg The file you're looking for is: https://github.com/ARMmbed/mbed-cli/blob/master/mbed/mbed_terminal.py

Let us know if you have any questions.

**Comment by thinkberg** [comment]
I will take a look, thanks.

**Comment by adbridge** [comment]
*Issue header has missing or incorrectly filled in fields! Please fix.*

**Comment by thinkberg** [comment]
PR in #789

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
