### ISSUE TITLE
Mbed compile -m detect picks incorrect target

### ISSUE THREAD

**Issue by gorankecman** [ARMmbed/mbed-cli#631]
`mbed compile -m detect -t gcc_arm` with a SEED_TINY_BLE plugged in will compile for the ARCH_BLE.

Original comment below

--------

I am a beginner with mbed and mbed-cli, and I have a problem which I need help for. If I selected a wrong place to ask this question, please forgive me and point me to the right place. I thought this might be related to mbed_cli, but also it might be related to arm gcc compiler. 

Description: 
I have created simple LED blink example with the online mbed compiler and compiled for Seeed Tiny BLE target and after compiling everything is as expected and LED blinks.

Then I wanted to compile same code with mbed-cli to get the offline capability.
1. I have exported code from the online compiler and selected GCC (ARM Embedded) toolchain.
Then I have executed following commands with given output:
```
$ mbed compile -m ARCH_BLE -t GCC_ARM
[mbed] ERROR: The mbed tools were not found in "/home/user/MBED/mbed_blinky_26022018". 
[mbed] ERROR: Run `mbed deploy` to install dependencies and tools. 
---
$ mbed deploy
[mbed] WARNING: Program "mbed_blinky_26022018" in "/home/user/MBED/mbed_blinky_26022018" does not use source control management.
[mbed] WARNING: To fix this you should use "mbed new ." in the root of your program.
---
[mbed] Updating library "mbed" to rev #7130f322cb7e
[mbed] Downloading library build "7130f322cb7e" (might take a minute)
[mbed] Couldn't find build tools in your program. Downloading the mbed 2.0 SDK tools...
[mbed] Updating the mbed 2.0 SDK tools... 
$ mbed compile -m ARCH_BLE -t GCC_ARM
Building project mbed_blinky_26022018 (ARCH_BLE, GCC_ARM)
Scan: .
Scan: mbed
Scan: env
Compile [100.0%]: main.cpp
[Fatal Error] platform.h@29,10: device.h: No such file or directory
[ERROR] In file included from ./mbed/mbed.h:55:0,
                 from ./main.cpp:1:
./mbed/platform/platform.h:29:10: fatal error: device.h: No such file or directory
 #include "device.h"
          ^~~~~~~~~~
compilation terminated.

[mbed] ERROR: "/usr/bin/python" returned error code 1.
[mbed] ERROR: Command "/usr/bin/python -u /home/user/MBED/mbed_blinky_26022018/.temp/tools/make.py -t GCC_ARM -m ARCH_BLE --source . --build ./BUILD/ARCH_BLE/GCC_ARM" in "/home/user/MBED/mbed_blinky_26022018"
---
```
I do not know how to solve this error, so I have tried other approach to import project from URL with following commands and outputs:
```
$ mbed import http://os.mbed.com/teams/mbed/code/mbed_blinky/
[mbed] Importing program "mbed_blinky" from "https://os.mbed.com/teams/mbed/code/mbed_blinky" at latest revision in the current branch
[mbed] Adding library "mbed" from "http://mbed.org/users/mbed_official/code/mbed/builds" at rev #7130f322cb7e
[mbed] Downloading library build "7130f322cb7e" (might take a minute)
[mbed] Unpacking library build "7130f322cb7e" in "/home/user/MBED/mbed_blinky/mbed"
[mbed] Couldn't find build tools in your program. Downloading the mbed 2.0 SDK tools...
$ mbed compile -m ARCH_BLE -t GCC_ARM
Building project mbed_blinky (ARCH_BLE, GCC_ARM)
Scan: .
Scan: env
Scan: mbed
Compile [100.0%]: main.cpp
Link: mbed_blinky
Elf2Bin: mbed_blinky
+-------------------+-------+-------+------+
| Module            | .text | .data | .bss |
+-------------------+-------+-------+------+
| BUILD/ARCH_BLE    |   220 |     4 |   24 |
| [fill]            |    18 |     0 |   15 |
| [lib]/c_nano.a    |  2337 |   100 |   12 |
| [lib]/gcc.a       |  1640 |     0 |    0 |
| [lib]/mbed.a      |  1113 |     0 |   29 |
| [lib]/misc        |   220 |     8 |   28 |
| mbed/7130f322cb7e |  2963 |    12 |  208 |
| Subtotals         |  8511 |   124 |  316 |
+-------------------+-------+-------+------+
Total Static RAM memory (data + bss): 440 bytes
Total Flash memory (text + data): 8635 bytes

Image: ./BUILD/ARCH_BLE/GCC_ARM/mbed_blinky.hex
```
Hex file is successfully created and I have copied it to the mbed drive and the code is programmed to the target, but LED does not blink.
I have even tried to create a new project and just copy main.cpp but the result is the same.
For example with a command:
`$ mbed new mbed-classic-program --mbedlib`
At the end, the outcome is the same, LED does not blink. 

If I create OS mbed project following output is given:
```
$ mbed compile -m ARCH_BLE -t GCC_ARM
Building project mbed-os-example-blinky (ARCH_BLE, GCC_ARM)
Scan: .
Scan: mbed
Scan: env
Scan: FEATURE_BLE

Could not compile for ARCH_BLE: Target does not support mbed OS 5
```
So I assumed this is not an option for Seeed Tiny BLE board.

After comparing hex file generated by online compiler and the one generated localy, I have observed that they are different. I guess since they are compiled with different compiler and linked with different linker, this could cause the difference. Also, that difference is localized only to the end of file (last 10% of that file).

All the required tools were installed on Ubuntu 17.10:
```
python 2.7.14
pip 9.0.1
git 2.14.1
hg 4.3.1
arm-none-eabi-gcc 7.2.1 (20170904, revision 255204 - added to the system PATH)
srec_cat 1.58.D001
```

Can somebody help with this issue I have? At least some pointers would be helpful?
I am sorry in advance if I missed some topic or issue where this was already discussed, but after googling for a while I could not find the solution to this problem. 

Goran Kecman

**Comment by gorankecman** [comment]
Hi @theotherjimmy, 

Fist I have tried target SEEED_TINY_BLE and now when the code is flashed, LED blinks. Thank you very much for the help! However, it is strange why then this target is not detected when I execute:
```
$ mbed compile -m detect -t GCC_ARM
[mbed] Detected "ARCH_BLE" connected to "/media/user/MBED" and using com port "/dev/ttyACM0"
...
```
For the other part, I have also seen that file device.h is missing, but I do not know how to solve that. Can you clarify what does "incomplete clone" means? I exported working code from the online compiler and tried to build it. I do not know what could be incomplete there? Do you think I should copy file from the link you have provided to appropriate location? 

Thank you very much for the help, I appreciate it a lot. 

Goran Kecman

**Comment by theotherjimmy** [comment]
I'm glad we could get something working for you. I think the "ARCH_BLE" and "SEED_TINY_BLE" may be indistinguishable to the tools.

-----

>Can you clarify what does "incomplete clone" means?

I think that the `hg clone` that Mbed CLI did for you may not have completed correctly. You could try removing the `mbed` directory and running `mbed deploy` again, or you could copy the `mbed` directory from your working project into the one that contains the error.

> I do not know what could be incomplete there?

I thought that it might be missing some files that should be part of the mbed release

**Comment by gorankecman** [comment]
@theotherjimmy thank you for help! 
All the problems were coming from the target provided when compiling the code. I was able to export the project from the online compiler and to get working hex file (LED blinks). You can see the procedure from commands:
```
$ mbed compile -m SEEED_TINY_BLE -t GCC_ARM
[mbed] ERROR: The mbed tools were not found in "/home/user/MBED/mbed_blinky". 
[mbed] ERROR: Run `mbed deploy` to install dependencies and tools. 
---
$ mbed deploy
[mbed] WARNING: Program "mbed_blinky" in "/home/user/MBED/mbed_blinky" does not use source control management.
[mbed] WARNING: To fix this you should use "mbed new ." in the root of your program.
---
[mbed] Updating library "mbed" to rev #5571c4ff569f
[mbed] Downloading library build "5571c4ff569f" (might take a minute)
[mbed] Couldn't find build tools in your program. Downloading the mbed 2.0 SDK tools...
[mbed] Updating the mbed 2.0 SDK tools...                                       

$ mbed compile -m SEEED_TINY_BLE -t GCC_ARM
Building project mbed_blinky (SEEED_TINY_BLE, GCC_ARM)
Scan: .
Scan: env
Scan: mbed
Compile [100.0%]: main.cpp
Link: mbed_blinky
Elf2Bin: mbed_blinky
+----------------------------+-------+-------+------+
| Module                     | .text | .data | .bss |
+----------------------------+-------+-------+------+
| BUILD/SEEED_TINY_BLE       |   213 |     4 |   24 |
| [fill]                     |    21 |     0 |   15 |
| [lib]/c_nano.a             |  2337 |   100 |   12 |
| [lib]/gcc.a                |  1664 |     0 |    0 |
| [lib]/mbed.a               |  1693 |     4 |   69 |
| [lib]/misc                 |   220 |     8 |   28 |
| mbed/TARGET_SEEED_TINY_BLE |  2985 |    12 |  208 |
| Subtotals                  |  9133 |   128 |  356 |
+----------------------------+-------+-------+------+
Total Static RAM memory (data + bss): 484 bytes
Total Flash memory (text + data): 9261 bytes

Image: ./BUILD/SEEED_TINY_BLE/GCC_ARM/mbed_blinky.hex

$ mbed compile -m ARCH_BLE -t GCC_ARM
Building project mbed_blinky (ARCH_BLE, GCC_ARM)
Scan: .
Scan: env
Scan: mbed
Compile [100.0%]: main.cpp
[Fatal Error] platform.h@29,10: device.h: No such file or directory
[ERROR] In file included from ./mbed/mbed.h:54:0,
                 from ./main.cpp:1:
./mbed/platform/platform.h:29:10: fatal error: device.h: No such file or directory
 #include "device.h"
          ^~~~~~~~~~
compilation terminated.

[mbed] ERROR: "/usr/bin/python" returned error code 1.
[mbed] ERROR: Command "/usr/bin/python -u /home/user/MBED/mbed_blinky/.temp/tools/make.py -t GCC_ARM -m ARCH_BLE --source . --build ./BUILD/ARCH_BLE/GCC_ARM" in "/home/user/MBED/mbed_blinky"
---
```
Is there a command which can give me all the available targets? 
I have executed `$mbed target --supported` but there is no SEEED_TINY_BLE listed. 
I have also observed that more targets are listed when I misspell target name during compile procedure (for example `$ mbed compile -m SOMETHING -t GCC_ARM`). There must be a better way than this?
I have also found that SEEED_TINY_BLE is listed when execute: `$ mbed export --supported`, but I could not figure out that from help. 

Also, there is a possibility to use detect with compile option -m (which I already mentioned), but it does not give correct target name. That, in the end, can be misleading to beginners. The only reason for my problems was that I have used detect option to get target name. Is there some online list of supported targets and their names to use with mbed-cli? 

Additionally, just to mention, you were right for the clone problem. If I delete mbed directory and run
`$ mbed deploy` again, I was able to compile the code without the error regarding device.h include with both targets SEEED_TINY_BLE and ARCH_BLE. 
Once again, thank you very much for the help! 

Goran Kecman

**Comment by theotherjimmy** [comment]
@gorankecman I'll mark this as a bug and edit the top post to call out the detect problem as a bug.

**Comment by gorankecman** [comment]
@theotherjimmy just to once again give the output of the compile command with detect added:
```
$ mbed compile -m detect -t GCC_ARM
[mbed] Detected "ARCH_BLE" connected to "/media/user/MBED" and using com port "/dev/ttyACM0"
```
Seeed Tiny BLE board is connected to the USB port.

**Comment by screamerbg** [comment]
@gorankecman Could you please copy/paste the contents of the mbed.htm from both boards? I remember that there was a batch of boards from Seeed that had an overlapping DEVICE ID.

**Comment by gorankecman** [comment]
@screamerbg Sorry for the late response, I was working with another IC lately, and I didn't have the board with me for some time. Now it is back. 
Again, when I execute the following command, I get the output given below:
```
$mbed compile -m detect -t GCC_ARM
[mbed] Detected "ARCH_BLE" connected to "/media/user/MBED" and using com port "/dev/ttyACM0"
```
The output of mbed.htm file is given below: 
```
<!-- mbed Microcontroller Website and Authentication Shortcut -->
<!-- Version: 0203 Build: Oct 18 2014 09:38:49 Git Commit SHA: 27f92b0d3777ee40d140e7894eb3594b2a511b99 Git local mods:Yes-->
<html>
<head>
<meta http-equiv="refresh" content="0; url=http://mbed.org/device/?code=9009020305BB955CF847FAAD"/>
<title>mbed Website Shortcut</title>
</head>
<body></body>
</html>
```

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-449

**Comment by screamerbg** [comment]
@gorankecman Have you had time to check my comment above?

**Comment by theotherjimmy** [comment]
Please use the correct DAPLink for your target. Please reopen if you still have problems.
