### ISSUE TITLE
Document lack of Cygwin support

### ISSUE THREAD

**Issue by donatieng** [ARMmbed/mbed-cli#635]
Although we have a couple of issues open (#578, #299) referencing this, there is no mention in the docs that Cygwin is not supported:
https://os.mbed.com/docs/v5.7/tools/installation-and-setup.html

It would be great having either a mention in the docs, or (better!) the platform being detected at runtime with a warning such as "running mbed-cli within Cygwin, use at your own risks!".

**Comment by cmonr** [comment]
At the very bottom of README.md, this line exists:

"Currently Mbed CLI is not compatible with Cygwin environment and cannot be executed inside it (https://github.com/ARMmbed/mbed-cli/issues/299)."

Are we saying that we don't expect users to read the README, or that we should add more references around the codebase explicitly stating the Cygwin isn't supported?

**Comment by cmonr** [comment]
Another option would be to somehow trim or split up the current README. Imo, it does seem quite long.

@theotherjimmy @screamerbg

**Comment by donatieng** [comment]
Yes, it's very far down!
And there is no mention of it in the handbook.

**Comment by cmonr** [comment]
@sg- @AnotherButler Looping y'all in.

**Comment by screamerbg** [comment]
@cmonr Splitting the README might lead to another problem - "It's in the documentation but I couldn't find it (Ctrl+F)". Perhaps it's a question of shortening some of the Mbed CLI readme content @AnotherButler 

Also agreed that this should be in the handbook @AnotherButler

**Comment by AnotherButler** [comment]
This has been in the Handbook: https://os.mbed.com/docs/latest/tools/test-and-debug.html

**Comment by screamerbg** [comment]
Closing this issue. Let's follow-up in #578 instead. In my environment Cygwin v2.10 (latest) for Windows 10 64bit, Mbed CLI works just fine.
