### ISSUE TITLE
Consider adding an 'mbed new library' command

### ISSUE THREAD

**Issue by loverdeg-ep** [ARMmbed/mbed-cli#649]
### Description
- Type: Enhancement
- Related issue:  [handbook-#462](https://github.com/ARMmbed/Handbook/issues/462#issuecomment-374974978) , #655 , #648
- Priority: Minor

--------------------------------------------------------------

## Enhancement

**Reason to enhance or problem with existing solution**

* There is limited documentation for creating libraries
* There is a lot of unnecessary effort required to write a library for mbed OS

**Suggested enhancement**

Add a command to mbed-cli that generates:
 
* a default mbed_lib.json
* TEST directory containing a basic, working test

**Pros**

* Encourage library development for mbed
* Could encourage use of greentea test framework
* Reduce user effort to create a library
* Reduce user research required to understand how to create a library and configuration

**Cons**

* Implementation time?

**Notes**
* I would consider this a distinct "project type" from that which is created by mbed new
* This project may or may not need mbed-os to be imported; Though if the test framework is imported with mbed-os versus mbed-cli I assume we would need mbed-os.

**Comment by adbridge** [comment]
*Issue header has missing or incorrectly filled in fields! Please fix.*

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
