### ISSUE TITLE
Progress bar only goes up to 90%

### ISSUE THREAD

**Issue by LiyouZhou** [ARMmbed/mbed-cli#653]
v 1.5.0 osx Python 2.7.12
```
mbed add https://github.com/ARMmbed/mbed-bootloader-internal
[mbed] Adding library "mbed-bootloader-internal" from "ssh://git@github.com/ARMmbed/mbed-bootloader-internal.git" at latest revision in the current branch
Downloading |########--------------------------------------------------| 14.58
```

The progress bar above only ever goes up to 90.0% and it disappears at 90.0%.

**Comment by theotherjimmy** [comment]
@LiyouZhou I think that should be fine, so long as the operation is complete after the progress bar goes away.

**Comment by theotherjimmy** [comment]
It looks like the last bit is "checking out files" https://github.com/ARMmbed/mbed-cli/blob/master/mbed/mbed.py#L961-L962

@screamerbg This may be a bug with the parsing of that progress.

**Comment by screamerbg** [comment]
@LiyouZhou What version of Git do you use?

**Comment by screamerbg** [comment]
Just tried it on Git 1.9.5 (Windows), Git 2.2.0 (Windows) and Git 2.10.1 (standard Git on Mac). On all of these I get progress bar between 90% and 100%. @LiyouZhou Please let me know of you Git version so I can reproduce.

**Comment by screamerbg** [comment]
@LiyouZhou Also could you check the behavior when you import mbed-os? E.g.
```
$ mbed cache purge
$ mbed new test_program
```

**Comment by screamerbg** [comment]
Bump @LiyouZhou

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-448
