### ISSUE TITLE
Consider adding "mbed new target" command

### ISSUE THREAD

**Issue by loverdeg-ep** [ARMmbed/mbed-cli#655]
### Description
- Type: Enhancement
- Related issue:  #649 , #648 
- Priority: Major

--------------------------------------------------------------

## Enhancement

**Reason to enhance or problem with existing solution**

* There is limited documentation for creating custom targets
* Currently limited support for custom targets
* There is a lot of unnecessary effort required to implement a custom target

**Suggested enhancement**

Add a command to mbed-cli that generates:
 
* a default custom_targets.json
* TEST directory containing a basic, working test for a target

**Pros**

* Encourage custom target development for mbed
* Could encourage use of greentea test framework
* Reduce user effort to create a custom target
* Reduce user research required to understand how to create a custom target and configure it

**Cons**

* Implementation time?

**Notes**
* I would consider this a distinct "project type" from that which is created by mbed new

**Comment by sg-** [comment]
Does adding an 'easy command' to Mbed CLI solve the problems stated?

>There is limited documentation for creating custom targets
>Currently limited support for custom targets
>There is a lot of unnecessary effort required to implement a custom target

I think if we get to the bottom of these problems, it may or may not be necessary to have Mbed CLI create files for you. Also, what is the benefit from
>TEST directory containing a basic, working test for a target

**Comment by loverdeg-ep** [comment]
There are 3 distinct "project type" patterns that I, we, have come across  while developing with mbed-cli.

* application Project
* library Project
* custom target/bsp project

`mbed-cli new` covers creation of an "application project" by pulling in mbed-os and whatever else it does

My thinking was that if mbed new defaults to an application project by default `mbed new target` would initialize a new 'custom target project', and `mbed new library` would initialize a new 'library project'

@sg-  Adding the `TEST` directory with basic hello world test would encourage use of the test framework while also providing a basic application with which to test the custom board without having to write an application in the root directory of the target/BSP repository. The custom target could then be imported with mbed-cli or included as a git sub-module in an application project.

#649 & #648 follow similar reasoning.

Also, @theotherjimmy since we've been dancing around related topics for a while

**Comment by loverdeg-ep** [comment]
@sg- in this particular case, that being a "BSP project", no files with a main function would exist outside the TESTS directory.

It would be very similar to creating a target folder inside of "mbedOS/targets/TARGET_X/..." except:

* The target implementation folder resides outside of mbedOS
* mbedOS is included as an mbed .lib or git submodule in order to bring in mbedOS/tools and the rest of mbed OS

**Comment by adbridge** [comment]
*Issue header has missing or incorrectly filled in fields! Please fix.*

**Comment by loverdeg-ep** [comment]
@screamerbg @sg-  Any further developments or insight regarding this. The same conversation that prompted me to make this issue just happened for the 2nd or third time. 

Each time the conversation has been with a different developer, and each time we come to the same conclusion that I came to above.

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
