### ISSUE TITLE
Add python_requires '<3.0' to prevent python 3 issues

### ISSUE THREAD

**Issue by MaartenArits** [ARMmbed/mbed-cli#659]
I used pip to install Mbed-cli, by accident it installed under python 3.6. I think using [python_required](https://packaging.python.org/tutorials/distributing-packages/#id54) for distribution would fix this issue. I don't know enough to be sure but hopefully it would prevent this problem in the future.

**Comment by screamerbg** [comment]
@MaartenArits Thanks for the suggestion! This is now implemented and live in Mbed CLI 1.5.1
