### ISSUE TITLE
mbed import issue

### ISSUE THREAD

**Issue by oneway3124** [ARMmbed/mbed-cli#671]
C:\Users\dav>mbed --version
1.5.1

C:\Users\dav\Desktop>mbed import https://os.mbed.com/teams/mbed/code/mbed_blinky
/
[mbed] Importing program "mbed_blinky" from "https://os.mbed.com/teams/mbed/code
/mbed_blinky" at latest revision in the current branch

[mbed] Adding library "mbed" from "https://os.mbed.com/users/mbed_official/code/
mbed/builds" at rev #aa5281ff4a02
[mbed] Downloading library build "aa5281ff4a02" (might take a minute)

But it cannot be executed successfully.
I want to know how to fix it. Thanks a lot in advance if you can give me some help.

**Comment by oneway3124** [comment]
I think that this issue is an network issue, because this package of 300MB can be download by me quickly.
So the mbed.py create some error.

**Comment by cmonr** [comment]
@oneway3124 Could you post the output of the command when you run it with `-vv` ?

**Comment by oneway3124** [comment]
@cmonr I has tried to use your github code, as the following
https://github.com/cmonr/mbed-os-example-wifi
![image](https://user-images.githubusercontent.com/3787176/40340968-cfeb129a-5db4-11e8-947c-e5f66e89bb2f.png)
Is it ok?

**Comment by cmonr** [comment]
@oneway3124 `-vv` is meant to be appended to the command as an additional parameter.

So instead of running `mbed import mbed-os-example-wifi`, the command would be `mbed -vv import mbed-os-example-wifi`

**Comment by oneway3124** [comment]
I has done successfully now.
