### ISSUE TITLE
mbed-cli should list compatible pip version as a dependency

### ISSUE THREAD

**Issue by RomanSaveljev** [ARMmbed/mbed-cli#673]
Through the hardship we have learned about https://github.com/ARMmbed/mbed-cli/blob/66f734d1cfb889a1f09e577d61e53c3006e3fcaf/README.md#mbed-cli-and-pip-compatibility, however for the better user experience, I think, it would be more useful, if its compatible version subset was included to `install_requires` in the `setup.py`. Then, possibly, pip itself would warn us, if we try to break the compatibility.

**Comment by cmonr** [comment]
Hmm... So on the one hand, I completely agree, but with release 1.6.0, the pip issue has been resolved. And as far as I know, the fix is backwards compatible across older pip versions.

@screamerbg Thoughts on adding pip version to setup.py?

**Comment by teetak01** [comment]
If definately should be improved. There is no guarantee that it would not break again later, or break a bit differently in future.

**Comment by screamerbg** [comment]
@teetak01 Agreed and following that thought, all requirements.txt in Mbed OS should be updated to limit to major releases of Python dependencies they have. As you said, there's no guarantee that they won't break in the future.

cc @cmonr @theotherjimmy

**Comment by adbridge** [comment]
*Issue header has missing or incorrectly filled in fields! Please fix.*
