### ISSUE TITLE
Export issue: 'izip' is not found

### ISSUE THREAD

**Issue by flipflop22** [ARMmbed/mbed-cli#684]
Hi I tried to export mbed-os-example-wifi using this command
`mbed export -i eclipse_gcc_arm -m UBLOX_EVK_ODIN_W2 --profile mbed-os/tools/profiles/debug.json`
then I always get this error,
`[mbed] ERROR: Unknown Error: global name 'izip' is not defined
---`

**Comment by AriParkkila** [comment]
It seems to be broken in the latest release. As a workaround, you can downgrade to working version, e.g.:
pip install mbed-cli==1.6

**Comment by flipflop22** [comment]
Right. I also just found it
