### ISSUE TITLE
custom_targets.json overwrites are not taken into account

### ISSUE THREAD

**Issue by drahnr** [ARMmbed/mbed-cli#685]
mbed-os 5.7

`custom_targets.json`

```
    "OUT_TARGET_XZY": {
        "default_toolchain": "GCC_ARM",
        "inherits": [
            "NRF52_DK"
        ],
        "macros_add": [
            "MBED_TICKLESS",
            "CONFIG_NFCT_PINS_AS_GPIOS",
            "SOFTDEVICE_NONE",
            "NDEBUG=1",
            "OS_TASKCNT=3",
            "OS_IDLESTKSIZE=32",
            "OS_STKSIZE=4096",
            "OS_TIMERS=3",
            "OS_FIFOSZ=4",
            "OS_MUTEXCNT=3",
            "MBED_FAULT_HANDLER_DISABLED=1"
        ],
        "device_has_add": [
            "FLASH"
        ],
        "device_has_remove": [
            "TRNG"
        ],
        "macros_remove": [
            "S132",
            "SOFTDEVICE_PRESENT",
            "CONFIG_GPIO_AS_PINRESET",
            "BLE_STACK_SUPPORT_REQD"
        ],
     ....
}
```

Still has `S132` defined as compilation parameter. `SOFTDEVICE_PRESENT` on the other hand is removed successfully by this setup.

This is also true if this chunk is appended to `mbed-os/targets/targets.json`

---

Workaround - remove the macro it in the `mbed_app.json`: 
```
{
	"target_overrides": {
		"*": {
             // ....
		},
		"OUT_TARGET_XZY" : {
			"target.macros_remove" : ["S132"]
		}
	},
        //...
}
```
which defeates the prupose of using a `custom_targets.json`

**Comment by theotherjimmy** [comment]
https://github.com/ARMmbed/mbed-os/blob/mbed-os-5.7/targets/targets.json#L3454-L3499

Is the offending target definition. It looks like you should be able to remove S132 from the macros, and if SOFTDEVICE_PRESENT is correctly removed, then that should be too.

**Comment by drahnr** [comment]
But that is exactly the point - S132 is not removed when done within a `custom_target.json` target definition. It works fine within an `mbed_app.json`

**Comment by theotherjimmy** [comment]
@drahnr Does it only affect `S132`? is there any other macro that behaves similarly? If there is we might have a pattern here. Further, any fixes for this behavior (supposing that there is a bug) will come to 5.9.0 or later.

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-442

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
