### ISSUE TITLE
Duplicate linker files - unhelpful error message

### ISSUE THREAD

**Issue by drahnr** [ARMmbed/mbed-cli#687]
```
[ERROR] 'GCC_ARM' object has no attribute 'info' 
```
when I accidentally had two linker files in my project directory.

```
$ mbed --version
1.7.2
```

**Comment by theotherjimmy** [comment]
@drahnr Yep see https://github.com/ARMmbed/mbed-os/pull/6914

**Comment by adbridge** [comment]
*Issue header has missing or incorrectly filled in fields! Please fix.*

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
