### ISSUE TITLE
separate build subdir for each build profile

### ISSUE THREAD

**Issue by bmcdonnell-ionx** [ARMmbed/mbed-cli#700]
Feature/behavior request: make the default build dir for `mbed compile` a subdir under `BUILD/`. Name the subdir the same as the name of the build profile file, without extension.

[EDIT: revised paths in table.]

e.g.

| Command                                                       | Build Dir                                          |
| ------------------------------------------------------------- | -------------------------------------------------- |
| `mbed compile`                                                | `BUILD/<target>/<toolchain>/develop/`              |
| `mbed compile --profile debug`                                | `BUILD/<target>/<toolchain>/debug/`                |
| `mbed compile --profile=myprofiles/superoptimized-cpp11.json` | `BUILD/<target>/<toolchain>/superoptimized-cpp11/` |

This way users can switch between build profiles without having to rebuild everything, and without having to specify custom build dirs.

(Re: the first example, `mbed-os/tools/profiles/develop.json` is the default build profile, right?)

**Comment by bmcdonnell-ionx** [comment]
I suggest parsing from the build profile filename once it is found on the file system, not from the command line. That way, on a case-insensitive filesystem, e.g. `mbed compile --profile debug` and `mbed compile --profile DEBUG` don't create duplicates.

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-679

**Comment by 0xc0170** [comment]
I think this is similar to the one #615 (might be duplicate)

**Comment by bmcdonnell-ionx** [comment]
Closed as dupe of #615.
