### ISSUE TITLE
MAX32620HSP OS5 support

### ISSUE THREAD

**Issue by amitchone** [ARMmbed/mbed-cli#701]
Hi, 

Trying to compile a project (using the CLI tools) that is verified working with the online compiler using the MAX32620HSP board. 

`mbed compile -m MAX32620HSP -t ARM`
`>> Building project KYM_BIO-HSP (MAX32620HSP, ARM)`
`>> Scan: .`
`>> Scan: mbed`
`>> Scan: env`
`>> Scan: FEATURE_BLE`
`>> Could not compile for MAX32620HSP: Target does not support mbed OS 5`

The board is visible to my system using `mbed detect`:

`[mbed] Detected MAX32620HSP, port COM4, mounted G:, interface version 0242:`
`[mbed] Supported toolchains for MAX32620HSP`
`+--------+-----------+-----------+-----+---------+-----+-------+`
`| Target | mbed OS 2 | mbed OS 5 | ARM | GCC_ARM | IAR | ARMC6 |`
`+--------+-----------+-----------+-----+---------+-----+-------+`
`+--------+-----------+-----------+-----+---------+-----+-------+`
`Supported targets: 0`

The board _is_ OS5 compatible. Not entirely sure what I'm doing wrong if there's no issue. Let me know what info would help!

Adam

**Comment by theotherjimmy** [comment]
Sorry, That board is not OS5 compatible: https://github.com/ARMmbed/mbed-os/blob/master/targets/targets.json#L2858

**Comment by amitchone** [comment]
That leaves me ever more confused.. The [platform listing](https://os.mbed.com/platforms/MAX32620HSP/) states OS5 compatibility and compilation via the online tool works just fine using OS5?

**Comment by theotherjimmy** [comment]
The second bit is a bug. It should fail in the online compiler with the same message as the offline compiler.

**Comment by amitchone** [comment]
Is there a published timeline for official inclusion of OS5 support available? Thanks for your help.

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-690

**Comment by theotherjimmy** [comment]
@amitchone I don't think there are any open PRs that add "5" into the release versions list I linked above.

**Comment by theotherjimmy** [comment]
@screamerbg @maclobdell @bentcooke This is venturing into your department.

**Comment by screamerbg** [comment]
Bump @maclobdell @bentcooke

**Comment by amitchone** [comment]
Regarding the above reference (#7345), could that be due to the removal of support for this platform?
