### ISSUE TITLE
Error when using baudrate

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/mbed-cli#707]
Error:

```make.py: error: unrecognized arguments: --baudrate 115200```

As per docs: https://github.com/ARMmbed/mbed-cli#serial-terminal

Instructions to reproduce:

```mbed compile -t GCC_ARM -m K64F -f --sterm --baudrate 115200```

Environment:
- Mbed CLI 1.7.3
- Windows 10 and OSX El Capitan

**Comment by screamerbg** [comment]
@theotherjimmy Yes, it's an option to `mbed sterm`, not to `mbed compile --sterm`

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-861

**Comment by MarceloSalazar** [comment]
My bad, this is indicated in the docs and I confirm works ok.
