### ISSUE TITLE
Program one of multiple platforms connected

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/mbed-cli#713]
This is an enhancement request.

I have many platforms connected to the USB port.

I'd like to compile and program one platform using this command:
```mbed compile -t <toolchain> -m <platform> -f```
This is very useful because finds the binary, detects the platform and programs it.

However, there is currently a limitation:
```[mbed] ERROR: Only 1 target board should be connected to your system.```

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-1063

**Comment by theotherjimmy** [comment]
At least we need a better error message, with a "next step" for the user.
