### ISSUE TITLE
Program wrong platform

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/mbed-cli#714]
Issue: defect.

I compile an application and want to program a platform using this option:
```mbed compile -t <toolchain> -m <platform> -f```

However, if have a **different** platform connected, that's ignored and the binary I've just compiled is used to program the wrong platform.

Solution / proposal:

It should detect that I don't have that platform detected and display the corresponding error.

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-1062
