### ISSUE TITLE
ssl certificate error when using pip command

### ISSUE THREAD

**Issue by jeromecoutant** [ARMmbed/mbed-cli#715]
Hi

In our network, we got SSL error when using "pip" command in mbed command line :-(

Do you think it is possible to add "--trusted-host=pypi.org" in mbed.py script ?

Regards,

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-1145

**Comment by cmonr** [comment]
I don't see why not.

But would you mind posting the output of that SSL error?

**Comment by jeromecoutant** [comment]
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),)) - skipping

ST IT security.... :-(
