### ISSUE TITLE
Get 'sterm' baud rate from mbed_app.json file

### ISSUE THREAD

**Issue by BlackstoneEngineering** [ARMmbed/mbed-cli#720]
## Problem
default speed on 'sterm' command is 9600, but a bunch of the mbed 'golden code' uses 115200 as the default speed. This creates a usability issue where users expect the 'mbed compile --flash --sterm' command to 'just work' and it doesnt. 

## Solution
Get default baud rate from mbed_app.json, specifically the `"platform.stdio-baud-rate": 115200` variable.

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-1387

**Comment by ConradBraam** [comment]
Will, doing this also make the port selection less random? When I have multiple targets connected, sterm appears to randomly select one of them, and not use my "mbed config target" value to find the correct port.
currently it's intuitive to add --baudrate 115200, but not to have to specify my target all over again when I type.
'mbed sterm --baudrate 115200' 
and want to be able to omit the port name please.

**Comment by BlackstoneEngineering** [comment]
@ConradBraam , no that is a different issue, please open it as a seperate ticket. 

To add extra info for my case, i like to use the `mbed compile --flash --sterm` command, but if the example code uses 115200 as its baud rate the command `mbed compile --flash --sterm -b 115200` does not work, instead I need to use `mbed compile --flash; mbed sterm -b 115200`, because these are two seperate commands I will often lose the first bits of info coming across the serial terminal, this is expscially problematic for bootloader debug messages. 

I would like to see the sterm sub command expanded to support baud rate so that this command would work `mbed compile --flash --sterm -b 115200` or something similar

**Comment by ConradBraam** [comment]
Will do, raised as mbed-cli/issues/793 . Many tiny improvements together make this toolchain easier to wield.

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
