### ISSUE TITLE
Request to change MBED_OS_DIR config name to MBED_OS_TOOLS_DIR

### ISSUE THREAD

**Issue by yennster** [ARMmbed/mbed-cli#722]
After getting some help for a different issue from @theotherjimmy he pointed out this PR https://github.com/ARMmbed/mbed-cli/pull/626 that adds support for a global config param called `MBED_OS_DIR`

From my understanding, this param basically allows you to not have to download the Mbed OS tools multiple times over your many Mbed OS 2 or 5 projects. However, this config param does not allow you to use the same copy of the entire `mbed-os` directory within multiple projects, just the tools and I guess `targets.json`. So I would like to see this config be renamed to `MBED_OS_TOOLS_DIR` or something similar to be more accurate to it's actual purpose/function.

Thanks!

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-1417

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
