### ISSUE TITLE
`mbed update` does not pull from master when updating to branch with empty sha

### ISSUE THREAD

**Issue by cmonr** [ARMmbed/mbed-cli#724]
When running `mbed update <branch>` on a project, if the mbed-os.lib file has no sha, I expect that the HEAD of master branch from mbed-os should be pulled and used (similar to how specifying no other information when doing a git clone <url> pulls the master HEAD). 

This is not the case.

### Steps to reproduce
```
> mbed import https://github.com/cmonr/mbed-os-example-blinky
...
[mbed] Adding library
 "mbed-os" from "https://github.com/ARmmbed/mbed-os" at rev #50bd61...

> cd mbed-os-example-blinky
> cd mbed-os; git status; cd ..
On branch mbed-os-5.9
Your branch is up to date with 'origin/mbed-os-5.9'.

> mbed update empty_mbed-os_sha
...
[mbed] Updating library "mbed-os" to latest revision in the current branch

> cd mbed-os; git status; cd ..
On branch mbed-os-5.9
Your branch is up to date with 'origin/mbed-os-5.9'.
```

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-1433

**Comment by theotherjimmy** [comment]
@cmonr The tag (should be branch, 'cause it moves) `latest` is used whenever possible. This is what happens when you use that tag. I think thin is intended behaviour

**Comment by cmonr** [comment]
Using `latest` would be fine as well.

Come to think of it, it's not even going to the "latest revision in the current branch" correctly.
If it did, then in this example, it should have jumped from 5.9.0 to 5.9.3, since that's all in the mbed-os-5.9 branch.

Using `latest` makes sense since it's also a part of the mbed-os-5.9 branch and would/should fir the "latest revision in the current branch" behavior.

**Comment by theotherjimmy** [comment]
@cmonr Latest is a tag, so it won't be automatically updated by git. This is expected behavior, and working as designed.
