### ISSUE TITLE
Downloading library build, takes very long, progress bar?

### ISSUE THREAD

**Issue by janjongboom** [ARMmbed/mbed-cli#726]
On an Mbed 2 project I'm running `mbed deploy`.

Then it says:

```
[mbed] Downloading library build "a330f0fddbec" (might take a while)
```

It's been doing this for over 10 minutes already. I have a very fast internet connection (200 mbps). What is it doing and can I have a progress bar similar to when we clone Mbed OS?

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-1448

**Comment by theotherjimmy** [comment]
@janjongboom Good suggestion. We could have a progress bar to indicate to users "get a cup of coffee".

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.

**Comment by josuah** [comment]
This might be caused by this instead:
https://github.com/ARMmbed/mbed-cli/issues/968

We might get a rush of users encountering this bug as soon as Ubuntu switches from python2 to pyhon3 by default.
