### ISSUE TITLE
Consider using .gitignore rather than .git/info/exclude

### ISSUE THREAD

**Issue by cblack-lab651** [ARMmbed/mbed-cli#732]
Since .git/info/exclude is not version controlled by default, using .git/info/exclude only works on the original developers program/repo.

Why is this used instead of .gitignore?  It is very annoying when working with a team, if one person adds a library only their local repo has the correct git ignore settings.

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-1508

**Comment by cmonr** [comment]
@screamerbg Would you mind shedding some light on this? Feels odd to me as well.

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
