### ISSUE TITLE
Disabling toolchain config

### ISSUE THREAD

**Issue by teetak01** [ARMmbed/mbed-cli#740]
Pretty basic question, how do I remove my local toolchain configuration? I did not find any information in manual. Default is mentioned as "none".

Setting mbed toolchain none sets none as toolchain instead of disabling it. Same with null or 0.

**Comment by theotherjimmy** [comment]
`mbed config -U` "unsets" configuration.

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-1572

**Comment by teetak01** [comment]
Thanks!
