### ISSUE TITLE
mbed test --unittests requires a target and a toolchain to be specified

### ISSUE THREAD

**Issue by lorjala** [ARMmbed/mbed-cli#742]
mbed test --unittests fails to run if target and toolchain are not specified or .mbed file with those values do not exist.

Commands like `mbed test --unittests -m K64F -t GCC_ARM` can be confusing for users and in CI since unit tests do not use any target or toolchain (gcc compilers are used).

**Comment by lorjala** [comment]
@OPpuolitaival @theotherjimmy Can we do anything about this?

Having different tools under the same command with shared options can cause inconsistencies like this.

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-1585

**Comment by OPpuolitaival** [comment]
@theotherjimmy can we make target and toolchain optional and check in case of icetea or greentea? Then mbed unitttest command looks better.

**Comment by OPpuolitaival** [comment]
Fix: https://github.com/ARMmbed/mbed-cli/pull/743

**Comment by theotherjimmy** [comment]
Thanks for the bug report. 1.8.0 will release with the fix in #743
