### ISSUE TITLE
No ability to select API host with `mbed dm` command

### ISSUE THREAD

**Issue by dhwalters423** [ARMmbed/mbed-cli#745]
Currently, the Mbed CLI tool defaults to the production api.mbedcloud.com instance of Pelion Device Management.

While this is okay for most customers, there should be an optional argument `-s` that allows you to specify the instance of Pelion Device Management, such as api-os2.mbedcloudstaging.net.

There are 2 reasons for this:

- Internal testing (not critical)
- Support for Pelion On Premises deployment, which will have a different DNS address

**Comment by yogpan01** [comment]
Agreed with @dhwalters423. We have requirement to support Cloud on-prem solution where the Cloud deployment is not Production but customer specific deployment.

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-1596

**Comment by theotherjimmy** [comment]
@dhwalters423 does `mbed config -G CLOUD_API_HOST` not work?

**Comment by theotherjimmy** [comment]
@dhwalters423 Why `-s`?

**Comment by yogpan01** [comment]
@theotherjimmy `-s` would represents own cloud environment. API key is specific to account inside a given environment.

**Comment by dhwalters423** [comment]
@theotherjimmy -G CLOUD_API_HOST is not documented anywhere.

**Comment by theotherjimmy** [comment]
@dhwalters423 We can fix the documentation issue.

@yogpan01 I was asking why `-s` was picked over other letters, not what it's supposed to mean. Sorry for the confusion.

**Comment by dhwalters423** [comment]
@theotherjimmy sounds good to me.

**Comment by adbridge** [comment]
@dhwalters423 Is there a PR addressing this issue ?

**Comment by theotherjimmy** [comment]
@cmonr They're not new options. They're just re-used options.
