### ISSUE TITLE
Feature: Need to be able to provide own certificate for 'device management'

### ISSUE THREAD

**Issue by teetak01** [ARMmbed/mbed-cli#748]
Currently I do not see any option how I could provide my own developer-certificate for the init-command.

There should be some flag which allows user to supply their own dev.c file.

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-1609

**Comment by teetak01** [comment]
I think effectively we just need a flag/variable to tell the tool to skip the certificate fetching and expect to find valid certificate in the execution folder. Or it could be something like:

0/null (disabled, expect functional cert in folder)
1 (auto-fetch, default)
"string.c" (user-supplied certificate. (maybe something to consider).

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
