### ISSUE TITLE
Q: whitelist of features  -- reasoning?

### ISSUE THREAD

**Issue by drahnr** [ARMmbed/mbed-cli#761]
I tried to define a custom feature as part of my `custom_targets.json` by simply adding

```
..
    "features_add": [
      "WINC_X509_ATMEL"
    ],
..
```

which resulted in:
```
[ERROR] Feature 'WINC_X509_ATMEL' is not a supported features
```

From the forum post at https://os.mbed.com/questions/79187/Custom-Targets/ hinted that it might have to do with a whitelist of features -- I verified that the whitelist is still present and in use:

```
    # Allowed features in configurations
    __allowed_features = [
        "UVISOR", "BLE", "CLIENT", "IPV4", "LWIP", "COMMON_PAL", "STORAGE", "NANOSTACK","CRYPTOCELL310",
        # Nanostack configurations
        "LOWPAN_BORDER_ROUTER", "LOWPAN_HOST", "LOWPAN_ROUTER", "NANOSTACK_FULL", "THREAD_BORDER_ROUTER", "THREAD_END_DEVICE", "THREAD_ROUTER", "ETHERNET_HOST"
        ]
```

What is the intention of this whitelist?
Why is this feature essentially disabled for me unless I start patching the mbed-os tree?

**Comment by theotherjimmy** [comment]
Originally, features were something that took up space within a binary without being used. They were originally used to help easily trim down that space usage. Now we have a strong design goal around space usage, and much better tools for exploring exactly what is used. I'm no longer convinced that we need the whitelist.

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
