### ISSUE TITLE
Compiling with more than one thread causes failures

### ISSUE THREAD

**Issue by Zeppelin15** [ARMmbed/mbed-cli#764]
Hi,

I've been trying to compile the standard blinky example using GCC_ARM. 
Invoking the standard `mbed compile -t GCC_ARM -m K64F` causes compilation to fail at random locations. Compilations can be completed with multiple `mbed compile -t GCC_ARM -m K64F` calls.

An example of failure output message : https://pastebin.com/2Gz2DGD0

I have noticed specifying `-j 1`  allows compilation to complete successfully first time.

Is there some preferred version of python or gcc that will allow multi thread compilation ?
What is the default number of jobs when no `-j` is specified?

### Versions
**OS :** Windows 10
**Python :** 2.7.13
**Mbed CLI** : 18.1 1.8.2
**Mbed Version** : 5.8 , 5.9 5.10
**GCC** : 6.3.1 , 7.2.1

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-1727

**Comment by theotherjimmy** [comment]
Hi @Zeppelin15 I have used GCC Versions between 4 and 8 without issues of that variety. It looks like printing is failing! That's very unusual. 

> What is the default number of jobs when no `-j` is specified?

In that case the number of jobs = the number of logical cpus in the machine (hardware threads included).

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
