### ISSUE TITLE
Erasing flash exclusively or before flash

### ISSUE THREAD

**Issue by nmaiti** [ARMmbed/mbed-cli#768]
I couldn't  locate any erase partition/flash use case in mbed-cli. I may be missing it but I see NVstored partitions are not getting erased during reflash using -f command.

**Comment by theotherjimmy** [comment]
@nmaiti reflash's behavoir is 1) not controlled by Mbed CLI and is controlled by the debug circuit and 2) generally depends on the file extension: .bin erases all flash and .hex erases only what is specified.

As we don't currently have any understanding of a "partition" or "NVStore" in the build tools or mbed CLI, I don't see how there is much we can do here.

**Comment by nmaiti** [comment]
mbed-cli compile -f option not erasing full flash, as its writing binary to flash, but keeping old nvstore data. Is it something unexpected behavior? using st F32M757 board.

**Comment by theotherjimmy** [comment]
@nmaiti I'm not sure what exactly you're asking about. `mbed compile -f` copies the binary to the device. At that point it's implementation defined what that binary does.

**Comment by evedon** [comment]
Considering the question has answered so closing this issue.
