### ISSUE TITLE
Upload to custom boards

### ISSUE THREAD

**Issue by masoudr** [ARMmbed/mbed-cli#769]
Hi,
I'm using an STM32F4 custom board. Is there any option that I can upload the compiled project after `mbed compile` to my board through CLI. Custom boards don't support drag and drop programming, so it should be programmed using external programmer software. It would be good if you add a custom upload option to CLI.
Thanks.

**Comment by theotherjimmy** [comment]
Hi @masoudr,

You're correct: we don't currently have an option to use custom programming software. If it's a somewhat standard interface firmware configuration, perhaps we could integrate support for it into the programming/flashing implementation (currently in htrun).

**Comment by masoudr** [comment]
@theotherjimmy Currently there are some platforms like `platformio` that has this option. I think CLI can be easily integrated with some tools like `openocd`.

**Comment by theotherjimmy** [comment]
@masoudr That's a good point: htrun (the implementation of -f) has a pyocd plugin for both flash and reset. Perhaps this would be sufficient for your use case?

**Comment by masoudr** [comment]
@theotherjimmy Actually I haven't tested `htrun` but it seems good. Does it have the ability to upload with both external programmer and serial port (dfu)? It would be better to integrate it with `mbed compile`. Currently, I'm using [this method](https://os.mbed.com/docs/v5.9/tutorials/visual-studio-code.html) to debug but there is no method for only uploading.

**Comment by theotherjimmy** [comment]
> . Does it have the ability to upload with both external programmer and serial port (dfu)?

Not that I'm aware of

> It would be better to integrate it with `mbed compile`.

`mbed compile` imports htrun to flash, so anything that htrun can flash, `mbed compile` can flash.

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
