### ISSUE TITLE
export to cmake_gcc_arm generates Cmake project that will not link

### ISSUE THREAD

**Issue by SteveOss** [ARMmbed/mbed-cli#772]
Version 1.8.2 using mbed-os-example-blinky

Exporting with:  mbed export -i cmake_gcc_arm  -m K64F 

In generated CMakeLists.txt

# executable mbed-os-example-blinky
ADD_EXECUTABLE(mbed-os-example-blinky
  cmake-build-debug/CMakeFiles/3.12.3/CompilerIdC/CMakeCCompilerId.c
  cmake-build-debug/CMakeFiles/3.12.3/CompilerIdCXX/CMakeCXXCompilerId.cpp
  cmake-build-debug/CMakeFiles/feature_tests.c
  main.cpp
  ...

Here link fails as there are multiple definitions on main in the first 4 files. Commenting out the first
three files fixes the problem. The CMake feature test executables are being incorrectly added.

**Comment by theotherjimmy** [comment]
@SteveOss What have you done to make sure that they're not added?

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-101*

**Comment by SteveOss** [comment]
Just removed them from the list.

**Comment by SteveOss** [comment]
@theotherjimmy I didn't actually do anything more than actually removing the offending files from the CMake file. Adding an ignore file is probably a good solution, but wasn't sure what determines how many CMake feature tests are required, or if they need to be separately built. In short. not enough of a CMake expert :)

**Comment by theotherjimmy** [comment]
@SteveOss I'm not either. If Mbed CLI add those to the CMakeFile, then you could use `.mbedignore` to remove them. I have not seen this behavior before, and I think it's Mbed CLI working as designed. I think.

**Comment by SteveOss** [comment]
@theotherjimmy Looks like all feature test programs are under a CMakeFiles sub directory, think the generator should simply filter these out, when generating the list of files to compile.

**Comment by theotherjimmy** [comment]
@SteveOss And how would it know to do that? is this a result of running:
 1. `mbed export ...`
 2. `cmake && make`
 3. `mbed export ...`
Which may not be supported.

**Comment by SteveOss** [comment]
@theotherjimmy Yes is a result of "mbed export -i cmake_gcc_arm". The bug is with the "mbed export"
function, the fix is to update the export function to filter out CMake test executable files. I was assuming you (Well actually this group) was responsible for maintaining/fixing this utility?

**Comment by theotherjimmy** [comment]
@SteveOss I'm trying to determine if this happens on the first run of `mbed export` or the second, and if you must run `cmake` between these runs of `mbed export`. If you could provide me with that information, I could help you workaround this in the mean time, and fix this longer term. I realize that the above is worded rather antagonistically. I don't mean to come off that way, and I can't think of another way to word this.

-------------------------

Maybe we could approach this from another direction. This is an open source project and you can submit bug fixes too. https://github.com/ARMmbed/mbed-os/tree/master/tools/export/cmake is the code that implements the exporter your using. There's a bunch of infrastructure around that, so please ask questions.

**Comment by SteveOss** [comment]
@theotherjimmy It happens of the first run of mbed export.

**Comment by theotherjimmy** [comment]
This makes me question if your project builds at all. Does `mbed compile -t gcc_arm -m <your-target>` work?

-----------------

You can instruct Mbed CLI to ignore those files by placing an `.mbedignore` file in the root with the following contents:
```
cmake-build-debug/CMakeFiles/*
```

**Comment by SteveOss** [comment]
@theotherjimmy As I stated initially. The generated project does not compile unless I manually remove the problematic files or as you suggest add an .mbedignore. Both approaches fix the problem, but the bug is that the export function generates something that is not correct in the first place, both of these solutions are work arounds.

**Comment by theotherjimmy** [comment]
> but the bug is that the export function generates something that is not correct in the first place

I'm suggesting that's not true at all: if it happens on first export, then these files are already present after `mbed import` and _any_ export or compile will fail in the same way.

**Comment by SteveOss** [comment]
@theotherjimmy Have just checked with a clean build and you are correct. It's a subsequent export that is picking up files generated by cmake (i.e the feature test executables). I guess is an edge case here but could probably be fixed by adding a black list to the python script that finds sources to build and excluding any in a CMakeFiles directory.

**Comment by theotherjimmy** [comment]
>  I guess is an edge case here but could probably be fixed by adding a black list to the python script that finds sources to build and excluding any in a CMakeFiles directory.

That's not how I would solve this, as the only case I'm aware of that causes this bug is running a build/export after the `cmake_gcc_arm` exporter has run. My preferred solution would be to enhance the CMake exporter to append files it knows CMake will generate into the blacklist. This has the advantage of keeping CMake-specific knowledge contained in the CMake exporter, and reduces the number of potential stumbling blocks for people who dos't use CMake as part of their Mbed project development environment.

**Comment by SteveOss** [comment]
"My preferred solution would be to enhance the CMake exporter" - Agreed, this is "the python script"
which searches for files to build and adds them to a CMake template.

**Comment by theotherjimmy** [comment]
>  this is "the python script" which searches for files to build and adds them to a CMake template.

Well, the CMake exporter shares the searching infrastructure with all other exporters and `mbed compile`. It's generic so that it can be shared among all of these parts. In other words, it's not quite that simple, and it would be quite a bit more difficult to maintain if each exporter had it's own scanning code!

Anywho, you have a workaround and we have a path toward a more robust solution.
