### ISSUE TITLE
Never able to complete regenerating index.json

### ISSUE THREAD

**Issue by Ronny-Liu** [ARMmbed/mbed-cli#773]
Partner reported command 'mbed export -i uvision --update-packs' will never get completed in a day or two.  I can reproduce this and watched it will hang at around 900(or less)/914.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-113*

**Comment by cmonr** [comment]
What's funny is that if I try to do this within my VM, my tmpfs partition is filled up really quickly.

Will continue testing.
