### ISSUE TITLE
How to ignore error when compile ?

### ISSUE THREAD

**Issue by zeecy-zhao** [ARMmbed/mbed-cli#788]
I cant find such build option that can ignore build error and go on compiling.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-167*

**Comment by theotherjimmy** [comment]
@zeecy-zhao There is no such option.

**Comment by screamerbg** [comment]
@theotherjimmy Perhaps the fundamental question is whether there should be one. What do you think?

**Comment by bridadan** [comment]
What would be the goal of ignoring build errors? If you continued to try and compile the project, what would happen when it got to the end? Linking the project not be possible.

@zeecy-zhao would you mind detailing your use case a bit more? If there was such an option, what would you expect the behavior to be?

**Comment by zeecy-zhao** [comment]
@bridadan 
just like  "make -k"

>        -k, --keep-going
            Continue as much as possible after an error.  While the target that failed, and those that depend on it, cannot be remade, the other dependencies of these targets can be processed all the same.

**Comment by kjbracey-arm** [comment]
I guess the use case is to plough on compiling as much as you can to keep the CPU occupied, while you fix the error you saw scrolling past, reducing the development cycle time as there's less remaining to compile after making the fix.

Would be annoying unless errors and progress indications were piped to different streams, or progress updates were reduced to just a bar or something. Or might work well with something like an Eclipse CDT error parser?

**Comment by zeecy-zhao** [comment]
@kjbracey-arm
Even working with eclipse cdt, the parser result could be different with command.

**Comment by bridadan** [comment]
Ah thanks for clarifying @zeecy-zhao. Would require some modifications to the toolchain logic in Mbed OS, but might not be too bad. Any thoughts @theotherjimmy?

**Comment by theotherjimmy** [comment]
We could make it happen. I'm not planning on doing it, but I can help provide guidance to anyone that wants to contribute it.

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
