### ISSUE TITLE
New command for coding style formatting

### ISSUE THREAD

**Issue by 0xc0170** [ARMmbed/mbed-cli#792]
`mbed format` command or similar for the formatting the code according to the Mbed OS coding style (using astyle , .astylerc option we provide as part of the OS, plus also .astyleignore file to ignore folders).

We have format code button in the online IDE - online and offline code formatting. It would help contributors to conform to our styling guide. We currently run commands locally (for bigger changes it is non trivial command).

Our next minor version 5.11 is going to have 0 coding style issues.

cc @sg-

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-174*

**Comment by bulislaw** [comment]
+1 but format can be confusing, so I'd rather use astyle/style/code-format.

**Comment by SeppoTakalo** [comment]
I would prefer `mbed astyle` or just a `.sh` script in the root that runs the Astyle.

I'm not fan of hiding behind `mbed ...` what we actually do.

**Comment by mark-edgeworth** [comment]
@SeppoTakalo I agree. If formatting to some sort of mbed style is appropriate for contributors then this needs to be documented for contributors only and provided as a config file for whatever tool is doing the formatting. This is not going to be mbed CLI, so I'm closing this.
