### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by bmcdonnell-ionx** [ARMmbed/mbed-cli#799]
In the [Compiling your program](https://github.com/ARMmbed/mbed-cli#compiling-your-program) section of `README.md`, the [our build profiles](https://docs.mbed.com/docs/mbed-os-handbook/en/latest/dev_tools/build_profiles/) and [toolchain profiles](https://docs.mbed.com/docs/mbed-os-handbook/en/latest/advanced/toolchain_profiles/) links are broken.

I didn't check the rest of the links on the page; there may be more.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-252*
