### ISSUE TITLE
mbed compile should respect MBED_OS_DIR

### ISSUE THREAD

**Issue by bearsh** [ARMmbed/mbed-cli#803]
`mbed target -S` respects `MBED_OS_DIR` as expected but `mbed compile` not, there one have to specifiy it again using the `--source` switch. that's confusing, so why not, if in the current dir, the `mbed-os` folder is absent and `MBED_OS_DIR` is set, add it to the source list.
that's a little but against the proposal in #722. alternatively why not split `MBED_OS_DIR` into `MBED_OS_TOOLS_DIR` and `MBED_OS_SOURCE_DIR`?

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-320*

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
