### ISSUE TITLE
Minimum setuptools version needed

### ISSUE THREAD

**Issue by cmonr** [ARMmbed/mbed-cli#806]
If a user installs Python 2.7.11 (the minimum install req according to the docs), setuptools is incredibly outdated. Solution was to update setuptools with `pip install -U setuptools`.

Stdout of issue: 
```
c:\python27\lib\distutils\dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
c:\python27\lib\distutils\dist.py:267: UserWarning: Unknown distribution option:  'long_description_content_type'
   warnings.warn(msg)
```

CC @pan-, who found the problem with a fresh version of 2.7.11 on Windows.

##### Note

Not sure if issue should be opened here or in PyOCD, which is what uses those two keys.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-344*

**Comment by bridadan** [comment]
I'm not aware of a way to specify a minimum setuptools version in `setup.py`, are you @cmonr? A quick search didn't turn up anything either. We could just document something along the lines of:

> Ensure you have the latest Python setuptools: `pip install --upgrade setuptools`
> Install mbed-cli: `pip install mbed-cli`

**Comment by screamerbg** [comment]
@cmonr Are you happy to issue a PR?

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
