### ISSUE TITLE
Require a way to build Mbed OS 2 applications using a custom built mbed library (for a custom platform)

### ISSUE THREAD

**Issue by deece** [ARMmbed/mbed-cli#807]
I am currently trying to port some Eclipse projects that use a manually built mbed library over to mbed-cli.

I need a custom library as I have custom device options & linker scripts (one is for a bootloader, so I need a tight binary, with a number of features disabled & LTO enabled to get the size down, the other has a custom linker script to place the binary at the offset that the bootloader expects). This is currently achieved with new targets added to targets/targets.json, but I think it should probably be handled as a project-specific override instead.

When creating a new mbed project with --mbedlib, there seems to be no way to avoid using a precompiled library and instead either build one with my custom options, or provide a path to my own pre-built library.

My platform is a derivative of NUCLEO_F030R8, which is not supported by MBedOS 5.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-348*

**Comment by deece** [comment]
Update: I've bodged a solution by adding "5" to the releases for my platform, then using .mbedignore to disable components that don't compile. It's pretty hacky...

**Comment by naveenkaje** [comment]
Hi @deece 
Thanks for bringing this to our attention. You are right. That's the current behavior and we are aware of it. We hope to address these pain points in the next major release.

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.

**Comment by adbridge** [comment]
Apologies, this was closed in error by the automated bot - re-opening.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTBTOOL-466*
