### ISSUE TITLE
How to get rid of the error tip ?

### ISSUE THREAD

**Issue by prowan** [ARMmbed/mbed-cli#819]
I have exported a project to eclipse, and then set the Build command in eclipse as follow:

mbed-cli compile -j0 -t GCC_ARM -m NUCLEO_F767ZI --profile mbed-os/tools/profiles/debug.json

This works well, but how to get rid of the error tip in eclipse as illustrated in this picture, thank a lot !
![image](https://user-images.githubusercontent.com/21994103/50873744-3bf35580-13fc-11e9-8120-28955e371d9a.png)

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-407*

**Comment by theotherjimmy** [comment]
@prowan Thanks for including the paths that you added. Those are pretty specific to your install of gcc, including the version. I wonder if there is a way to get eclipse to add those for us.

**Comment by linlingao** [comment]
It appears your issue has been resolved. We'll be closing this.
