### ISSUE TITLE
Compiles to .hex and not to .bin

### ISSUE THREAD

**Issue by Akselvb** [ARMmbed/mbed-cli#825]
Hello!

When trying to compile, the following happens:

<img width="526" alt="screenshot 2019-01-15 at 10 42 38" src="https://user-images.githubusercontent.com/11042389/51173411-ac471e80-18b5-11e9-8c27-8a5b6958e37d.png">

The resulting build is compiled as a .hex file instead of a .bin file. However, an _Update Image_ is created as a .bin file. This happens for all projects. Is it correct output?

**Comment by teetak01** [comment]
Hi @Akselvb, yes this is expected output. The `Image` is the one you should flash to your board. `Update image` is used by Device Management update feature, and that only works with .bin format images, thus the default output there is .bin. You can also override this to output  also the update image as .hex (or something else) if you need the update image to be of different format.

Is this an issue for you, or are you just wondering why this changed?

The change was done to have more streamlined support for Pelion device management update when compiling the application firmware image in .hex format. This way you do not need to edit the mbed_app.json to recompile the whole application to get updatable image in .bin format.

**Comment by Akselvb** [comment]
Hi @teetak01, thank you for answering. It is no issue, more than a confusion whether that was the reason my compilation is failing. Only seeing .bin files as Images, I thought it might be the reason for the following compilation error:

<img width="625" alt="screenshot 2019-01-15 at 12 00 32" src="https://user-images.githubusercontent.com/11042389/51176458-38107900-18bd-11e9-841b-b9cf9c468700.png">

I thought the generated .hex file maybe was bigger than the corresponding .bin, causing the overflow.

However, when I change target from _NRF52_DK_ to _EFM32GG11_STK3701_ (larger flash), it compiles and I get a .bin file:

<img width="623" alt="screenshot 2019-01-15 at 12 03 03" src="https://user-images.githubusercontent.com/11042389/51176558-8756a980-18bd-11e9-8ebb-f212f3d56705.png">

Is the format of the compiled image MCU-dependent?

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-486*

**Comment by Akselvb** [comment]
The last link is dead.

**Comment by 0xc0170** [comment]
> Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-486

@Akselvb This is internal ticket reference to keep track of the external issues internally.

**Comment by theotherjimmy** [comment]
> Is the format of the compiled image MCU-dependent?

Yes.

See https://os.mbed.com/docs/mbed-os/v5.11/reference/adding-and-configuring-targets.html, `OUTPUT_EXT` section.
