### ISSUE TITLE
Readme / Wiki pages broken links

### ISSUE THREAD

**Issue by marcin-ch** [ARMmbed/mbed-cli#839]
I believe it refers exclusively to `README.md`, links like [Creating and importing programs](https://github.com/ARMmbed/mbed-cli#creating-and-importing-programs) and [Importing an existing program](https://github.com/ARMmbed/mbed-cli#importing-an-existing-program) seem to be broken.

Could you please review it.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-831*

**Comment by theotherjimmy** [comment]
Which readme are you referring to? The README in the root simply refers to the documentation at os.mbed.com/docs

**Comment by naveenkaje** [comment]
@marcin-ch As @theotherjimmy pointed out, https://github.com/ARMmbed/mbed-cli/blob/master/README.md links to https://os.mbed.com/docs/mbed-os/v5.11/tools/developing-mbed-cli.html -> https://github.com/ARMmbed/mbed-cli/blob/1.8.3/README.md#creating-and-importing-programs/https://github.com/ARMmbed/mbed-cli/blob/1.8.3/README.md#importing-an-existing-program. Can you please let us know which URLs don't work for you?

**Comment by marcin-ch** [comment]
@theotherjimmy @naveenkaje I have some links saved, and they are for example as follows (and mentioned in my first post):
[Creating and importing programs](https://github.com/ARMmbed/mbed-cli#creating-and-importing-programs) = `https://github.com/ARMmbed/mbed-cli#creating-and-importing-programs`
[Importing an existing program](https://github.com/ARMmbed/mbed-cli#importing-an-existing-program) = `https://github.com/ARMmbed/mbed-cli#importing-an-existing-program`

So as you can see, they are different than you pointed out.
I am pretty sure that above links referred to instructions available under `README.md`. It looked like below in the picture (it has been prepared in Paint):
![Click to see the image](https://raw.githubusercontent.com/marcin-ch/issue839/master/mbed_cli_readme.png)

So, did it change recently? I am pretty sure I did save links in December '18 and they worked then just fine. Now, I can see only [Introduction](https://github.com/ARMmbed/mbed-cli#introduction)

Hope that is clear now.

**Comment by marcin-ch** [comment]
Now I see here in online docs, section [Developing: Mbed CLI](https://os.mbed.com/docs/mbed-os/latest/tools/developing-mbed-cli.html) the note that:
**You can find our legacy CLI documentation in the [README](https://github.com/ARMmbed/mbed-cli/blob/1.8.3/README.md).**

@theotherjimmy @naveenkaje @bridadan thanks then for all the explanation and your support!
