### ISSUE TITLE
mbed compile -m <DEVICE> should set <DEVICE> as default device

### ISSUE THREAD

**Issue by LiyouZhou** [ARMmbed/mbed-cli#844]
Because mbed dm, mbed test, mbed compile could use the default device, it would be useful to update the default device to the latest compiled target.

**Comment by teetak01** [comment]
This needs be enforced more strictly. I stumbled on this with K64F being my default target, but I was working on F429ZI board and ended up uploading K64F image to my board as I did not notice the tool was automatically picking up wrong image.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-867*

**Comment by theotherjimmy** [comment]
@LiyouZhou It already does, when you have no default target.

**Comment by LiyouZhou** [comment]
but would be nice if it becomes the default.

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
