### ISSUE TITLE
mbed dm init without API key gives out ugly backtrace, it would be better to handle the exception

### ISSUE THREAD

**Issue by teetak01** [ARMmbed/mbed-cli#845]
Currently if I run "mbed dm init ..." without any API-key defined, it gives quite long backtrace from cloud-sdk which can be confusing to understand.

It would be more clear to catch this Exception and point to either use "-a" flag to provide the API-key, or define CLOUD_SDK_API_KEY parameter.

**Comment by bridadan** [comment]
Hi @teetak01, I'm currently doing this in an mbed-os PR: https://github.com/ARMmbed/mbed-os/pull/9635

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-866*

**Comment by cmonr** [comment]
@teetak01 Mind retesting with master? It just came in :)
