### ISSUE TITLE
'mbed new' overwrites existing mbed_app.json

### ISSUE THREAD

**Issue by JammuKekkonen** [ARMmbed/mbed-cli#848]
running mbed new command to existing codebase which includes mbed_app.json will overwrite the contents of mbed_app.json

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-872*

**Comment by theotherjimmy** [comment]
@aashishc1988 Could you look into this?

**Comment by bridadan** [comment]
Oops, I had already started a fix (twas quite quick): https://github.com/ARMmbed/mbed-cli/pull/850
