### ISSUE TITLE
mbed config not properly documented

### ISSUE THREAD

**Issue by TacoGrandeTX** [ARMmbed/mbed-cli#862]
@theotherjimmy As we discussed, ```mbed config``` should:
 * accept any variable even if useless
 * produce proper output for ```--help``` - it doesn't correctly list the variables that actually have an affect

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-943*

**Comment by theotherjimmy** [comment]
We discussed that `mbed config` should only accept the variable that it understands.

**Comment by naveenkaje** [comment]
Submitted https://github.com/ARMmbed/mbed-cli/pull/865
