### ISSUE TITLE
Print path of source file during compile

### ISSUE THREAD

**Issue by paradajz** [ARMmbed/mbed-cli#879]
Currently, mbed compile will output only the filename of the file being compiled, ie.

```
...
Compile [ 20.1%]: cipher_wrap.c
...
```

But later, when the build is finished, full path relative to the source directory is printed:

`| mbed-os/features/mbedtls/src/cipher_wrap.o                                   |    826 |     0 |    0 |`

Is there an option to print the full path during compilation as well? If not, consider this a feature request. My usecase is the following:

I am using mbed-compile in Visual Studio Code. I wrote regex matcher which will catch any warnings or errors during compilation, so that I get screen like this in Visual Studio Code's problems tab:

![Screenshot_2019-04-01_11-32-12](https://user-images.githubusercontent.com/2544094/55317956-e5813a80-5471-11e9-8e72-6964410fa7f9.png)

The problem is when I click on reported problem, Visual Studio Code doesn't know the exact path of the file, since the assumption is $CURRENT_PROJ_PATH + filename caught during compile. Since compile only gives out filename without path, this won't work properly (the built path will be invalid).

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-1103*

**Comment by theotherjimmy** [comment]
Hi @paradajz. That's a good catch, and this could certainly be improved for consistency.  Perhaps you could be parsing the warning information directly instead of relying on progress info to print out exactly below their respective files. For reference, this is not always the case. progress and warnings may be intermingled at the moment.

**Comment by paradajz** [comment]
Yes, I've been considering just turning the verbose output on during the compile and catching the warnings/errors from GCC although this feels like a hack since the mbed-cli already uses different syntax. Having the file path in mbed-cli syntax would be much more elegant solution.

**Comment by theotherjimmy** [comment]
@paradajz As I said, that's not a good way to do things as I can't make certain that the errors/warnings always print after the file that generates them. We compile many files in parallel and we may print the "Compiling" for a file long before the warnings and many other "Compiling" statuses may appear between the two, making this an unreliable method of determining the source of an error or warning.

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
