### ISSUE TITLE
mbed dm init always chooses the first developer certificate

### ISSUE THREAD

**Issue by ryannowarm** [ARMmbed/mbed-cli#881]
It would be nice if mbed dm init allows the user to select which developer certificate gets downloaded.

**Comment by bridadan** [comment]
Thanks for the feedback! At the moment, we generally don't prompt users after running a command. Would selecting a certificate by name with a `--cert-name` option or something be workable?

**Comment by ryannowarm** [comment]
On Fri, Apr 05, 2019 at 08:59:30AM -0700, Brian Daniels wrote:
> Thanks for the feedback! At the moment, we generally don't prompt users after running a command. Would selecting a certificate by name with a `--cert-name` option or something be workable?
>

Hey Brian.  Yup a command line option would be best.  Probably something like
`--dev-cert-name` for clarity since there's already a `--certificate
CERTIFICATE` option to specify the manifest signing cert.
IMPORTANT NOTICE: The contents of this email and any attachments are confidential and may also be privileged. If you are not the intended recipient, please notify the sender immediately and do not disclose the contents to any other person, use it for any purpose, or store or copy the information in any medium. Thank you.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-1124*

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
