### ISSUE TITLE
Generate Clang compilation database

### ISSUE THREAD

**Issue by paradajz** [ARMmbed/mbed-cli#886]
It would be great if mbed compile could output [compile_commands.json](https://clang.llvm.org/docs/JSONCompilationDatabase.html) file containing the info about all compiled sources.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-1149*

**Comment by ladislas** [comment]
Would love to see that as well!

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.

**Comment by Pratyush-Mallick** [comment]
> It would be great if mbed compile could output [compile_commands.json](https://clang.llvm.org/docs/JSONCompilationDatabase.html) file containing the info about all compiled sources.

The mbed_studio does output the compile_commands.json file located at AppData\Local\Mbed Studio\programs\<project-name>\
