### ISSUE TITLE
Mbed CLI does not handle multiple output folders

### ISSUE THREAD

**Issue by teetak01** [ARMmbed/mbed-cli#887]
mbed-cli will fail to link if code is compiled to multiple different output folders.

For. ex.
running
```
mbed compile --build xyz
```
```
mbed compile
```
Will fail to link as it also tries to link everything under xyz/ folder also.

Maybe a simple fix would be that as part of --build <BUILD>, the tools generate .mbedignore file in the root of the <BUILD> folder.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-1158*

**Comment by teetak01** [comment]
I have no use case for this, just noticed this behaviour. I consider this quite trivial-level.

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.

**Comment by adbridge** [comment]
Apologies, this was closed in error by the automated bot - re-opening.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTBTOOL-462*
