### ISSUE TITLE
Mbed CLI tries to auto-install even when everything is up to date (hidapi on linux)

### ISSUE THREAD

**Issue by teetak01** [ARMmbed/mbed-cli#888]
[mbed] WARNING: Missing Python modules were not auto-installed.
       The Mbed OS tools in this program require the following Python modules: hidapi

The missing module check does not understand this line:
```
hidapi>=0.7.99,<0.8.0;platform_system!="Linux"

```

**Comment by bridadan** [comment]
@teetak01 Thanks for the bug report. Are you using Linux?

**Comment by teetak01** [comment]
Ubuntu 18.04, somehow forgot to mention that.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-1167*
