### ISSUE TITLE
ERROR: Unable to update "mbed-os" to rev #

### ISSUE THREAD

**Issue by mjohngreene** [ARMmbed/mbed-cli#895]
Using mbed-cli 1.8.3 on Windows 10, I get the following output for the mbed-os library when using "mbed update":

> [mbed] Updating library "mbed-os" to rev #16bac101a6b7 (tags: mbed-os-5.7.7, mbed_lib_rev160)
error: Could not fetch origin
[mbed] ERROR: Unable to update "mbed-os" to rev #16bac101a6b7 (tags: mbed-os-5.7.7, mbed_lib_rev160)

My project has another .lib file which updates fine as does the code from the project itself.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-1202*

**Comment by mjohngreene** [comment]
Oops!  I was using the incorrect Mbed command.  Should have been "deploy" instead of "update."
