### ISSUE TITLE
[Mbed-OS 5.13 OOB] mbed help command doesn't give ARMCC details

### ISSUE THREAD

**Issue by soleilplanet** [ARMmbed/mbed-cli#898]
mbed toolchain --help
```

Set or get default toolchain
This is an alias to "mbed config [--global] toolchain [name]"

positional arguments:
  name                 Default toolchain name. Example: ARM, GCC_ARM, IAR

optional arguments:
  -h, --help           show this help message and exit
  -G, --global         Use global settings, not local
  -S, --supported      Shows supported matrix of targets and toolchains
  -v, --verbose        Verbose diagnostic output
  -vv, --very_verbose  Very verbose diagnostic output

```
suggesting to add ARMC5 and ARMC6 descriptions for the 'help' page.
also, mbed_settings.py doesn't include ARMC6_PATH, which might be confusing.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-1272*

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
