### ISSUE TITLE
Mbed CLI should disable pip auto-install by default

### ISSUE THREAD

**Issue by teetak01** [ARMmbed/mbed-cli#899]
The tool should not auto-install pip components by default. Instead, this should be opt-in feature.

Some mbed features support --no-dependencies flag, but for. example mbed compile does not.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-1277*

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
