### ISSUE TITLE
Mbed sterm : add the type of parity bit as option

### ISSUE THREAD

**Issue by LaurentLouf** [ARMmbed/mbed-cli#901]
Hello,

I might be wrong since it is not defined anywhere, but from what I've tested, `mbed sterm` assumes that the serial format is `8N1` and there's no easy way to change that. It would be nice to be able to choose the data format completely, being able to change only the baud-rate is kind of frustrating (and, generally speaking, I don't like when a tool dictates something to my software, that is usually the other way around). Is that possible ?

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-1286*

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
