### ISSUE TITLE
mbed deploy doesn't work within a git worktree

### ISSUE THREAD

**Issue by pan-** [ARMmbed/mbed-cli#909]
I tried to use `mbed deploy` to deploy `.lib` file and it appears that it doesn't work within a git worktree. What can I do to work around that limitation ?

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTBTOOL-352*

**Comment by mark-edgeworth** [comment]
Could you provide a little more information as to what is not working for you please? For me, although the code does complain that the program does not use source control (which it does, albeit as a worktree), the deploy seems to do what is expected.

**Comment by mark-edgeworth** [comment]
Thanks for this! I've done a little digging on this myself. As you might know, the build tools for mbed OS support both git and mercurial as SCM systems. The tools distinguish between the two by looking for a directory called .git or .hg in the root. When operating a worktree, the .git directory is actually a file, and the tools don't handle this.
Whilst it is simple to fix this single issue, I'm concerned that changing this will bring in other potential problems that are related solely to the worktree concept. I am sorry for any problems that this may bring you. I will keep this issue on our backlog and see what we can do.

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.

**Comment by adbridge** [comment]
Apologies, this was closed in error by the automated bot - re-opening.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTBTOOL-461*

**Comment by mark-edgeworth** [comment]
To be honest we don't have the resource available to tackle this one.
