### ISSUE TITLE
No relative path/No quotes around path with spaces

### ISSUE THREAD

**Issue by mdeweerd** [ARMmbed/mbed-cli#920]
The Makefile that is generated does not add quotes around paths and/or does use relative paths.

After executing on my Win10 machine, the following command for generating the makefile:
````
   mbed export -vv -i GCC_ARM -m NUCLEO_F091RC --profile debug
````

Where `mbed --version` returns `1.8.3`

The makefile shows (project name and username replaced with <...>):

````
INCLUDE_PATHS += -I../c:/Users/<user>/Mbed Programs/<project>/mbed-os
ASM_FLAGS += -c:/Users/<user>/Mbed Programs/<project>/mbed-os
````

This filed compilation, I had to add the quotes:
````
INCLUDE_PATHS += -I../"c:/Users/<user>/Mbed Programs/<project>/mbed-os"
ASM_FLAGS += -I"c:/Users/<user>/Mbed Programs/<project>/mbed-os"
````

Notice however that the first path is a mix of an absolute and a relative path.

Most pats are relative like this:

````
INCLUDE_PATHS += -I.././mbed-os/usb/device/utilities/events
````

So it seems that the makefile should have read the following instead:

````
INCLUDE_PATHS += -I.././mbed-os
ASM_FLAGS += -I"././mbed-os"
````
Or similar, or determine the absolute path from the Makefile path.

Another issue exists with
```
C_FLAGS += .\mbed_config.h
````
Compiling using `c:\cygwin64\bin\make`, produced the error message that the file .mbed.config.h could not be found.

Changing that to
```
C_FLAGS += ./mbed_config.h
````
Fixed that.  Most paths are using forward slashes ("/"), but this path was an exception.  I guess this should change.

On a sidenote, I personnaly avoid using spaces in path names, it's a pity "Mbed studio" generates the program in "Mbed Programs" with a space.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTBTOOL-378*

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.

**Comment by mdeweerd** [comment]
IMHO these are defects.

Reasons:

1. The default path including the space "Mbed programs" is proposed by the tool itself;
2. As a result the generated Makefile is invalid for certain steps.
3. Inconsistency (backward slash instead of a forward slash) breaking the makefile is a defect.
4. The suggestions were only there to indicate how this can be solved.

I am not using MBED anymore at this time - I am not reporting this issue more than I am now.

**Comment by adbridge** [comment]
Apologies, this was closed in error by the automated bot - re-opening.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTBTOOL-459*

**Comment by mdeweerd** [comment]
Closing this as it has been stale for over 2 years to clean up my issues list.
