### ISSUE TITLE
Automatic flashing fails with multiple source directories?

### ISSUE THREAD

**Issue by Funky185540** [ARMmbed/mbed-cli#923]
Hello there,

I recently found this [article in the docs][1] (see "*Managing multiple Mbed projects*") that describes how to use one instance of the mbed library for multiple projects.  
Now I have setup a folder structure like this for testing purposes:
```
Multiple-Projects-Test/
`- mbed-os/
`- my_project/
`- BUILD/
```

And I call mbed-cli (from within the *Multiple-Projects-Test* folder) like this:
`mbed compile --build=BUILD/my_project/(...) --source my_project --source mbed-os -t GCC_ARM -m DISCO_F769NI -f`

But here comes the weird part:
- The binary file is built correctly, inside the correct build folder and it does what I'd expect it to.
- However, **flashing the MCU (through -f) fails, since it looks for a file called** `BUILD/my_project/(...)\Multiple-Projects-Test.bin`

Which is the name of the parent folder, whereas the path to the binary file is `BUILD/my_project/(...)\my_project.bin`

My Mbed-cli version is 1.10.1. 
Is this intended behaviour?

Kind regards,
Andreas

[1]: https://os.mbed.com/docs/mbed-os/v5.14/tools/working-with-mbed-cli.html

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTBTOOL-411*

**Comment by Funky185540** [comment]
Stumbled across a solution to my problem.
`mbed compile` has a CLI option `--artifact-name` that allows to specify the name of the bin file.

Could anybody add this to the docs [in the article that mentions this][2]?  
Sticking to the example used there but with automatic flashing it would be something like:

```
$ mbed compile -t ARM -m LPC1768 --source project1 --source mbed-os --build BUILD/project1 -f --artifact-name project1
$ mbed compile -t ARM -m K64F --source project2 --source mbed-os --build BUILD/project2 -f --artifact-name project2
```

Or correct me if I'm mistaken, but that's what works for me.


[2]: https://os.mbed.com/docs/mbed-os/v5.14/tools/working-with-mbed-cli.html
