### ISSUE TITLE
using cli not downloading mbed

### ISSUE THREAD

**Issue by D252874** [ARMmbed/mbed-cli#927]
i am just started using the cli for testing and development purpose i am waiting for it to download for longer than 20 min already then i thought i do some testing of your netwerk and when i ping mbed.com or os.mbed.com i get an timeout is that something with your protection or is it something with me with i doubt becouse any other website i ping gets an response in 4 a 5 ms

**Comment by D252874** [comment]
![downloading](https://user-images.githubusercontent.com/36726897/67203755-3e172580-f40c-11e9-9755-2b86d073f437.png)
![ping](https://user-images.githubusercontent.com/36726897/67203801-4ff8c880-f40c-11e9-803a-d0c901e6925c.png)
here are the testing i did and my cli

**Comment by loverdeg-ep** [comment]
This seems to be a common issue.

My teams solution has been to keep a mirror of mbed on our local network and clone it "manually" outside of mbed-cli.

**Comment by D252874** [comment]
that sound great but does that also work when you have't gotten it yet like download it from there website and then use that or doesn't that work ?

**Comment by loverdeg-ep** [comment]
Not sure. 
We don't use mbed-cli directly except for build/compile.

**Comment by D252874** [comment]
so now it is an day later and I still can't ping mbed maby something with security or some weird thing but now it says =
![image](https://user-images.githubusercontent.com/36726897/67265352-cef20d80-f4ad-11e9-8466-2cfa0c579fb4.png)
and I tryed running it as an admin and tryed it without windows explorer

**Comment by 40Grit** [comment]
@mark-edgeworth @0xc0170

**Comment by mark-edgeworth** [comment]
os.mbed.com doesn't seem to respond to ping, but it is alive (check it in a browser). Sounds like the earlier attempt to download mbed failed or was killed, and has now left behind an open file. Suggest that you check for open filehandles, or restart the machine might help...

**Comment by D252874** [comment]
could it be possible that it thinks it has it in the cache but it is not in the cache so it crashed

**Comment by D252874** [comment]
tested it and now i get this =
![image](https://user-images.githubusercontent.com/36726897/67281609-14273700-f4d0-11e9-8c77-e2ed89ed1b72.png)

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTBTOOL-443*

**Comment by D252874** [comment]
this looks a lot like issue [#436](https://github.com/ARMmbed/mbed-cli/issues/436) but i don't know what the problem is. and how to fix it
i did mbed deploy in an folder i created got this =
![image](https://user-images.githubusercontent.com/36726897/67370176-86ecec80-f57a-11e9-8bd3-b387862f82a0.png)
with an new problem with tagg --mbedlib

**Comment by D252874** [comment]
no i am making an project without --mbedlib and i get kind of an progress bar that i am not getting with the mbedlib i did do this with the very embose but it seems to work i am not getting no error. 

but found out i can't use this for the export i want for some reason
i will keep this here becouse i am maby gone use mbed cli but i need this to work for that

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
