### ISSUE TITLE
mbed Cli not working on Python 3.7

### ISSUE THREAD

**Issue by yasir-khilji-64** [ARMmbed/mbed-cli#933]
Fresh install of python 3.7. 
ran `pip install --user mbed-cli`
ran `mbed --help`
error 
mbed not recognized

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTBTOOL-482*

**Comment by mark-edgeworth** [comment]
Hi, we recommend using a virtual environment to run the mbed-cli tools. Using a fresh ```pipenv shell``` at version 3.7.4 I was able to ```pip install mbed-cli``` and run it without problems. Hope this helps to get you going on this.

**Comment by yasir-khilji-64** [comment]
OK. let me check this. 
Thanks for the suggestions

**Comment by yasir-khilji-64** [comment]
@mark-edgeworth still not working on Ubuntu. 
stuck on ```Adding library "mbed-os" from "https://github.com/ARMmbed/mbed-os" at branch/tag "latest"```
