### ISSUE TITLE
A wrong URL in the ARMmbed/mbed-cli repository

### ISSUE THREAD

**Issue by AndreySviyaz** [ARMmbed/mbed-cli#941]
There is a [bad URL](https://github.com/ARMmbed/mbed-cli/blob/master/README.md) in the Get started of the [README.rst](https://github.com/ARMmbed/mbed-cli)

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTBTOOL-514*

**Comment by mark-edgeworth** [comment]
Fixed in https://github.com/ARMmbed/mbed-cli/pull/950
