### ISSUE TITLE
Documentation link is broken

### ISSUE THREAD

**Issue by edoardesd** [ARMmbed/mbed-cli#946]
https://github.com/ARMmbed/mbed-cli/blob/master/README.md is not working

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTBTOOL-533*

**Comment by 0xc0170** [comment]
Where is this one coming from (documentation url) ? I can see it uses .md extension, instead of .rst

**Comment by mgrah** [comment]
Just open the .rst file and there's a link (see the original bug report) that doesn't work. 

https://github.com/ARMmbed/mbed-cli/blob/master/README.rst contains a link to https://github.com/ARMmbed/mbed-cli/blob/master/README.md 

The link is under the heading "Get Started" and the link text is "read the full documentation on GitHub". I'm sure that's not supposed to be a recursive link to itself. :)

**Comment by mark-edgeworth** [comment]
fixed in https://github.com/ARMmbed/mbed-cli/pull/950
